### PR TITLE
DOC: NEW: How to test a branch

### PR DESCRIPTION
**Pull request by tlimoncelli**
Issue:

We frequently give instructions on how to test a branch from memory.

Resolution:

Document this on the website so we can send a link instead.

### CODE REVIEW

**Comment by cafferata** [comment]
I've prepared the feedback in a new branch [cafferata/dnscontrol/tree/docs/test-a-branch-feedback](https://github.com/cafferata/dnscontrol/tree/docs/test-a-branch-feedback). Would you like to pull it? Or should I prepare a new GitHub pull request?

**Comment by tlimoncelli** [comment]
> I've prepared the feedback in a new branch [cafferata/dnscontrol/tree/docs/test-a-branch-feedback](https://github.com/cafferata/dnscontrol/tree/docs/test-a-branch-feedback). Would you like to pull it? Or should I prepare a new GitHub pull request?

I am not that sophisticated in my Github knowledge :-(.  Please walk me through what I should do (or create a github PR).

Thanks!

**Comment by cafferata** [comment]
```shell
cd dnscontrol
git checkout tlim_integr
```

**Merge branch**

```shell
git remote add cafferata git@github.com:cafferata/dnscontrol.git
git fetch cafferata docs/test-a-branch-feedback
git rebase cafferata/docs/test-a-branch-feedback --no-edit
git push
```

**Clean-up**

```shell
git remote remove cafferata
```

**Comment by tlimoncelli** [comment]
Thanks for the tips!

Changes look excellent!

**Comment by cafferata** [comment]
I suspect something went wrong. Commit https://github.com/StackExchange/dnscontrol/pull/3264/commits/6c0a4abbcb6400ad8f72e1450ad6240d58a3e333 reverts the previous changes.

I've recreated these branch/GitHub pull request

```shell
git checkout -B docs/test-a-branch-feedback
git cherry-pick 37cd87ff31b696fc598b95f90c9049de5e15250f
git cherry-pick da3c58b8468ab39d3aef2d1af186a084183b27ef
git cherry-pick 555f77da285f0c96faa694aac8c4dc0b940adc5a
git cherry-pick 57ad3cb308d8f3e2b689c1b8baad4f4a6ccde4d1
git cherry-pick 58423222dde59ce0d889a9ae7642b345a3df127a
```

**Pull request merged**
