### PR TITLE
perf(go sdk): introducing semver to HEXONET provider

### PR DESCRIPTION
**Pull request by Rashad-j**

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Thanks for the update!  Sadly for some reason this breaks `go list -mod=mod -u -m -json all`.  That seems small but that breaks a tool we use to find outdated depenencies:

```
tlimworkm1:~/git/dnscontrol$ go get -u github.com/psampaz/go-mod-outdated
go get: added github.com/mattn/go-runewidth v0.0.12
go get: added github.com/olekukonko/tablewriter v0.0.5
go get: added github.com/psampaz/go-mod-outdated v0.7.0
go get: added github.com/rivo/uniseg v0.2.0
tlimworkm1:~/git/dnscontrol$ go list -mod=mod -u -m -json all | go-mod-outdated -update -direct
go list -m: loading module retractions for github.com/juju/utils@v0.0.0-20200116185830-d40c2fe10647: no matching versions for query "latest"
+--------+---------+-------------+--------+------------------+
| MODULE | VERSION | NEW VERSION | DIRECT | VALID TIMESTAMPS |
+--------+---------+-------------+--------+------------------+
+--------+---------+-------------+--------+------------------+
```

**Comment by tlimoncelli** [comment]
By the way... this is an existing problem. It seems that `go mod tidy` adds something to `go.*` that causes the problem.  If you resubmit this PR without running `go mod tidy` everything works fine.

This script reproduces your steps:

```
#!/bin/bash

git checkout .
git checkout master
git branch -D hexver || true
git co -b hexver
sed -i.bak -e 's@github.com/hexonet/go-sdk/response@github.com/hexonet/go-sdk/v3/response@' providers/hexonet/error.go
sed -i.bak -e 's@github.com/hexonet/go-sdk/apiclient@github.com/hexonet/go-sdk/v3/apiclient@' providers/hexonet/hexonetProvider.go
go get github.com/hexonet/go-sdk/v3/apiclient
go get github.com/hexonet/go-sdk/v3/response
# This succeeds:
go list -mod=mod -u -m -json all | go-mod-outdated -update -direct
# This fails:
#go mod tidy
#go list -mod=mod -u -m -json all | go-mod-outdated -update -direct
```

**Comment by tlimoncelli** [comment]
Ah!  I think I found a much, much, more simple solution!

Just remove any lines in `go.*` that refer to the juju package:

```
go tidy mod
sed -i.bak -e '/github.com\/juju/d' go.*
```

That should be all we need!

**Comment by Rashad-j** [comment]
Hi @tlimoncelli 
I tried your last solution, however, the tests did not succeed, thus I applied the solution before. 
Let me know if you need any further changes.

**Comment by tlimoncelli** [comment]
Cool cool.

One last change: No need to check in the *.bak files.  Please remove them and then I'll merge the PR:

    git rm providers/hexonet/error.go.bak providers/hexonet/hexonetProvider.go.bak

Tom

**Comment by tlimoncelli** [comment]
Thanks for the update!  (Sorry it took so long!)

**Pull request merged**
