### PR TITLE
Support for all characters < u00FF

### PR DESCRIPTION
**Pull request by tresni**
TXT records should be able to support any character from \u0000 to \u00FF, but because of how runes past utf8.runeSelf are stored, this wasn't possible previously.  By interpreting all TXT records as Latin-1, we get conversion to proper byte sequences that can be stored in DNS records.

### CODE REVIEW

**Comment by tresni** [comment]
Example DSL that failed previously:

```
DEFAULTS(
	NAMESERVER_TTL('24h'),
	DefaultTTL('12h'),
	CF_PROXY_DEFAULT_OFF
);

var REG_NONE = NewRegistrar('none', 'NONE');

var DNS_BIND = NewDnsProvider('bind', 'BIND');

D('example.org', REG_NONE, DnsProvider(DNS_BIND),
    TXT("test", "\xff")
);
```

```
$ ./dnscontrol preview
******************** Domain: example.org
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: 'example.org'. Changes:
CREATE TXT test.example.org "\195\191" ttl=43200

----- Registrar: none...WARNING: No nameservers declared; skipping registrar. Add {no_ns:'true'} to force.
Done. 1 corrections.
```

It should create the record as `\255` but instead creates it as `\195\191` due to the encoding in golang.

**Comment by tlimoncelli** [comment]
I'm not sure if we should encourage people to stuff binary data in their TXT records but...

If we are going to support this, we should track which providers support it.  So far, none that I tested except Google:

Would you mind merging in this test?  https://github.com/StackExchange/dnscontrol/pull/955/files

**Comment by tresni** [comment]
BIND and PowerDNS both support it. Definitely not sure on the cloud provider side of things.

**Comment by tresni** [comment]
Side note does not look like there is anything additional in that branch to merge yet. Happy to add tests or modify to meet any requests.

**Comment by tlimoncelli** [comment]
Ah, I failed at git.  Tryi: https://github.com/StackExchange/dnscontrol/pull/956/files

**Comment by tresni** [comment]
@tlimoncelli I've merged your integration test and modified it a little to show that BIND actual does work (though there is a limitation in miekg/dns that has to be worked around right now.)

**Review by tlimoncelli — APPROVED** [review]
LGTM.  Ready for merge?

**Comment by tlimoncelli** [comment]
Note: Due to the way Github Actions handles secrets, the full tests can only run from a non-forked repo.  I cloned the repo into https://github.com/StackExchange/dnscontrol/pull/959 and all the tests pass.

In other news...

I've been thinking about this and I've decided that this should be a "capability" that providers have.  There is already `CanUseTXTMulti`, which marks which providers permit TXT records with multiple strings.  Could you redo this as `CanUseTXTBinary` so that we can indicate which providers support the full range of chars?  This way making exceptions in the validator and integration tests don't need to list individual providers.

By the way... I'm curious what inspired you to add this feature?  Is there an application that requires binary data in a txt record?  Protocol compliance/completeness?  If I knew that I'd be able to make better suggestions.

**Comment by tresni** [comment]
> I've been thinking about this and I've decided that this should be a "capability" that providers have. There is already `CanUseTXTMulti`, which marks which providers permit TXT records with multiple strings. Could you redo this as `CanUseTXTBinary` so that we can indicate which providers support the full range of chars? This way making exceptions in the validator and integration tests don't need to list individual providers.

Absolutely, I'll try to work on this this weekend.

> By the way... I'm curious what inspired you to add this feature? Is there an application that requires binary data in a txt record? Protocol compliance/completeness? If I knew that I'd be able to make better suggestions.

[DNSCrypt](https://dnscrypt.info/protocol) certificates are stored in TXT records and contain binary characters.  I've been working on a [tinydns provider](https://github.com/tresni/dnscontrol/tree/tinydns) and using a zone that contains these records when I noticed the issue.  I work in the DNS so yes, compliance/completeness are important to me too, but really it just scratched an itch for me ;-)

**Comment by tresni** [comment]
I haven't forgotten this, I just haven't had the time yet (unfortunately.)  Hoping to get to it soon(tm)

**Comment by tlimoncelli** [comment]
No worries! Thanks for checking in!

**Comment by tlimoncelli** [comment]
Please rebase (i.e. `get merge master`).

**Comment by tlimoncelli** [comment]
Due to the many changes to TXT handling, the rebase would be very difficult.  I've made this PR instead: https://github.com/StackExchange/dnscontrol/pull/1088

**Comment by tresni** [comment]
Thanks, unfortunately life had some major changes for me in the last while and I'm just now getting my head above water.  Thank you for following up with this.  I'll close this PR in favor of #1088

**Comment by tlimoncelli** [comment]
Life happens.  Hope things are ok!

**Pull request closed without merging**
