### PR TITLE
MSDNS: Document pssession options

### PR DESCRIPTION
**Pull request by shodges-vermeer**
Added optional variables of psusername and pspassword

Found in source code at dnscontrol/providers/msdns/powershell.go

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Those settings are untested.  Have you used them successfully?  My reading of the code says they should work, but I'm not in a position to test them.

**Comment by shodges-vermeer** [comment]
Ahh okay. I'm running into issues with getting it to work, but it may be unrelated to the credentials portion. Let me do some more digging and I'll get back to ya.

**Comment by shodges-vermeer** [comment]
Authentication appears to be working if my understanding of order of operations is correct. When running `dnscontrol preview` it should (I believe) authenticate before echoing "******************** Domain: $domain:". 

For me, once it echos that it just hangs but I'm thinking it may be because a few of our zones are insanely large.

**Comment by tlimoncelli** [comment]
I'm not sure of the order of operations but, yes, large zones take a LONG time.

Fun story: When I was first writing this I thought there was a terrible bug because the zone processing was taking minutes.   I assumed forking the powershell from Go was super slow... that wasn't it at all.

It turns out the zone dump was a 100 MiB of JSON, 99% of which was data that got thrown away.  That's why there is `Select-Object -Property * -ExcludeProperty Cim*` to filter out the cruft.  It runs a lot faster now. 

If you see any improvements (other properties we could exclude), I'd be glad to optimize this further.

Tom

**Comment by tlimoncelli** [comment]
I'm merging this.  It sounds like it works... the slowness isn't related.  

Thanks for finding this and

**Comment by shodges-vermeer** [comment]
Thanks! Turns out it wasn't slow, just had some firewall rules or something in place that was preventing my laptop from hitting our DC directly. Once we opened that it worked flawlessly.

**Pull request merged**
