### PR TITLE
GCORE: Allow PTR records

### LINKED ISSUE #2889: Allow PTR records on GCore DNS
It can be used, on rDNS zones.

image

### PR DESCRIPTION
**Pull request by xtexChooser**
Closes #2889

## Release changelog section

* GCORE: Allow to add PTR records

### CODE REVIEW

**Comment by xtexChooser** [comment]
Tested:
```
xtex@exozyme ~ [1]> dig 0.c.6.1.7.0.1.b.e.0.a.2.ip6.arpa PTR @ns1.gcorelabs.net +noall +answer
0.c.6.1.7.0.1.b.e.0.a.2.ip6.arpa. 600 IN PTR    xvnet.eu.org.
```

**Comment by xtexChooser** [comment]
However, I found that I can't enable DNSSEC on rDNS zones (even if these zones are just freshly added to GCore, without any PTR or other records).
This means GCore can't be used as the authoritative nameserver for rDNS zones (at least, for IP from RIPE NCC).

**Comment by cafferata** [comment]
Ping @xddxdd because he is the maintainer of this DNSControl provider.

**Comment by xddxdd** [comment]
Looks good to me

**Comment by cafferata** [comment]
Thanks @xddxdd for the quick review.

**Comment by tlimoncelli** [comment]
Thanks, folks!

**Comment by xtexChooser** [comment]
FYI: GCore told me that they solved the [DNSSEC issue on arpa zones](https://github.com/StackExchange/dnscontrol/pull/2890#issuecomment-2028090280).

**Pull request merged**
