### PR TITLE
DESEC: Fix init

### PR DESCRIPTION
**Pull request by JenswBE**
This PR:

-  Introduces `searchDomainIndex` which populates the index on first request
-  Adapts `initializeDomainIndex` / `buildIndexFromResponse` to `fetchDomainIndex` / `appendDomainIndexFromResponse` which returns a domain index instead of updating `desecProvider` directly
-  Simplifies and clarifies structure of `desecProvider`
-  Trims leading and trailing whitespace from token

Fixes https://github.com/StackExchange/dnscontrol/issues/3014

Below integrations tests are currently failing. But I cross-checked before the PR changes and had the same result.

- 10: Attl:Change_TTL
- 11: TTL:Change_a_ttl
- 22: complex_TXT:a_0-byte_TXT
- 23: TXT_backslashes:TXT_with_backslashs
- 39: SRV:Change_TTL999
- 42: DS:DS_create
- 47: DNSKEY:Create_DNSKEY_record

### CODE REVIEW

**Comment by JenswBE** [comment]
Just tried to apply an existing domain on deSEC with the change. While the `push` works, it seems there is a bug in `preview`.

Before PR:
```
Domain Index initilized without pagination (1 domains)
******************** Domain: widv.be
Build rrset without pagination (2 rrs)
WARNING: Please contact support@desec.io if you need TTLs < 3600. Setting TTL of widv.be type TXT from 300 to 3600
Done. 0 corrections.
```

After PR:
```
******************** Domain: widv.be
WARNING: Zone 'widv.be' does not exist in the 'desec' profile and will be added automatically.
WARNING: No nameservers declared; skipping registrar. Add {no_ns:'true'} to force.
Done. 0 corrections.
```

I'll investigate tomorrow and push a fix.

**Comment by JenswBE** [comment]
I re-ran all integration tests after 01cf57995f2202c0ce01a51d3797a28d38168ba0 and they are still producing the same result as in the PR description.

Next to this, I previewed and pushed a few private domains to deSEC using code of this commit. All seem to work as  expected now.

@tlimoncelli  (or any other maintainer), could you please review this PR once you have some time?

**Comment by cafferata** [comment]
_Ping @D3luxee, the maintainer of the deSEC provider._

**Comment by JenswBE** [comment]
Binary built with `CGO_ENABLED=1 GO111MODULE=on go build --race -o ../dns/dnscontrol` (seems CGO is required for the race checker).

When running multiple times `ppreview` and `ppush` with 4 domains, it never triggered a race condition alert.

The only difference I noticed between concurrently and serially is the handling of non-existing domains. But it might be due to the implementation details of `ppreview`/`ppush`. If no such difference should exist, please let me know and I'll try to debug.

```
CONCURRENTLY gathering 4 zone(s)
SERIALLY gathering 0 zone(s)
```

**preview**
Counted towards the total corrections.
```
******************** Domain: tuinfeestbeerse.be
1 correction (desec)
#1: Create zone 'tuinfeestbeerse.be' in the 'desec' profile
INFO#1: Domain "tuinfeestbeerse.be" provider desec Error: failed fetching records for domain tuinfeestbeerse.be (deSEC): Not found.
```

**ppreview**
Not counted towards the total corrections.
```
******************** Domain: tuinfeestbeerse.be
WARNING: Zone 'tuinfeestbeerse.be' does not exist in the 'desec' profile and will be added automatically.
```

**push**
Domain created including all configured records.
```
******************** Domain: tuinfeestbeerse.be
To enable DNSSEC validation for your domain, make sure to convey the DS record(s) to your registrar:
...
Build rrset without pagination (1 rrs)
1 correction (desec)
#1: Changes:
...
SUCCESS!
```

**ppush**
Domain created without configured records
```
******************** Domain: tuinfeestbeerse.be
1 correction (desec)
#1: Create zone 'tuinfeestbeerse.be' in the 'desec' profile
To enable DNSSEC validation for your domain, make sure to convey the DS record(s) to your registrar:
...
SUCCESS!
INFO#1: Domain "tuinfeestbeerse.be" provider desec Error: failed fetching records for domain tuinfeestbeerse.be (deSEC): Not found.
```

**Comment by tlimoncelli** [comment]
Looks great! Thanks for this!

**Pull request merged**
