### PR TITLE
NEW FEATURE: IMPORT_TRANSFORM_STRIP

### PR DESCRIPTION
**Pull request by tlimoncelli**

### CODE REVIEW

**Comment by tlimoncelli** [comment]
@cafferata

**Comment by cafferata** [comment]
@tlimoncelli, how can I help? ☺️

**Comment by tlimoncelli** [comment]
> @tlimoncelli, how can I help? ☺️

Sorry for being unclear.  It updates the documentation thus I was looking for your feedback.

**Comment by cafferata** [comment]
The documentation about [IMPORT_TRANSFORM_STRIP](https://docs.dnscontrol.org/~/revisions/9RKqRBkKqzgGRq1s0xTh/language-reference/domain-modifiers/import_transform_strip) looks nicely. There's no feedback. ☺️

**Comment by tlimoncelli** [comment]
Thanks!

**Pull request merged**
