### PR TITLE
DIGITALOCEAN: Replace SetTargetTXTString use with a new function

### PR DESCRIPTION
**Pull request by Deraen**
Related to #1545

I've run the tests with the change.

### CODE REVIEW

**Comment by Deraen** [comment]
Looks like go fmt check for PRs is broken on CI, this doesn't change formating, and go fmt doesn't output anything for me locally.

**Comment by tlimoncelli** [comment]
@jpbede fixed the CI issue. Thanks for pointing that out!

**Comment by tlimoncelli** [comment]
Before we merge this, I'd like you to try something.

I recently realized that Cloudflare uses `SetTargetTXTfromRFC1035Quoted()` when it should be using SetTargetTXT().  This makes me wonder if other providers made the same mistake.

Sadly I can't think of a way for the integration tests to determine if the wrong function was used.

Does the DO API really return a single string that needs to be parsed?  I looked at the API documentation and it didn't say anything about how they store TXT records.

Could you try your PR using SetTargetTXT() instead?  It might require you to update auditrecords.go and add recordaudit.TxtNoStringsLen256orLonger and recordaudit.TxtNoMultipleStrings.

Thanks!

**Comment by tlimoncelli** [comment]
The problem is that I don't have a good way to explain to people under what situations its best to use (a) SetTargetTXTfromRFC1035Quoted or (b) SetTargetTXT + fix the bugs.  This is my problem to solve.  It's not about you.

The problem is that SetTargetTXTfromRFC1035Quoted will pass all integration tests... yet it is still the wrong choice.

My gut tells me that the right thing to do is:

Go to the web control panel. If it permits you to enter multiple strings, use SetTargetTXTfromRFC1035Quoted.  If it only permits a single string, switch to SetTargetTXT and fix the bugs. (Possibly adding to auditrecord.go to eliminate troublesome edge cases)
 
Sorry for being confusing.  This is kind of a mess and I'm struggling to find a way to put into words the entire situation.  I appreciate your patience.

**Comment by tlimoncelli** [comment]
The changes I made in https://github.com/StackExchange/dnscontrol/pull/1567 might fix this.

**Comment by tlimoncelli** [comment]
Fixed in https://github.com/StackExchange/dnscontrol/pull/1567

**Pull request closed without merging**
