### PR TITLE
add the new ANAME record type to the records list

### PR DESCRIPTION
**Pull request by pmoroney**
Since this ANAME/ALIAS record is new,

### CODE REVIEW

**Comment by tlimoncelli** [comment]
This looks great so far!

Not all providers support ANAME. Please mark which providers do support it:

* providers/providers.go: Add the constant CanUseANAME
* pkg/normalize/validate.go checkProviderCapabilities(): add ANAME to the list.
* Any provider that supports ANAME, mark this in providers/*/*provider.go

Basically if you search for CanUsePTR and CanUseSRV, you'll see what to do.

**Comment by pmoroney** [comment]
ANAME is what we are calling ALIAS records here at name.com, and we are already passing `providers.CanUseAlias` to the register function. I'm just adding the type to these functions since they list the valid types now because of the SRV change that got merged after I added support for this in https://github.com/StackExchange/dnscontrol/pull/156

**Comment by pmoroney** [comment]
Also it seems I got distracted and never finished my initial description up above ;)

**Comment by tlimoncelli** [comment]
Oh i see!  Yes, that makes sense now!

**Pull request merged**
