### PR TITLE
DOCS: add dhcid RR docs

### LINKED ISSUE #2695: DOCS: Missing DHCID DNS resource type
From the [Providers](https://docs.dnscontrol.org/service-providers/providers) > [Provider Features](https://docs.dnscontrol.org/service-providers/providers#provider-features) table the new DHCID DNS resource type is linked https://github.com/StackExchange/dnscontrol/pull/2417/files#diff-28e66bede643a7156cf9c19950731e1a3a9ab66becf1a063f7705076bfc4dbdaR90. However, there is (_currently_) no documentation page. The result? A GitHub 404 error.

cc: @fritterhoff can you perhaps help us with this?

### PR DESCRIPTION
**Pull request by fritterhoff**
Fixes #2695

### CODE REVIEW

**Comment by cafferata** [comment]
Thank you for this work! Can you also update the `dnscontrol.d.ts`? You can do this by running `go generate ./...`.

**Comment by fritterhoff** [comment]
Done

**Review by cafferata — APPROVED** [review]

**Comment by cafferata** [comment]
Thank you @fritterhoff. I see there is one more change needed:

`SUMAMRY.md`

```diff
    * [CAA_BUILDER](functions/domain/CAA_BUILDER.md)
    * [CNAME](functions/domain/CNAME.md)
+   * [DHCID](functions/domain/DHCID.md)
    * [DISABLE_IGNORE_SAFETY_CHECK](functions/domain/DISABLE_IGNORE_SAFETY_CHECK.md)
    * [DMARC_BUILDER](functions/domain/DMARC_BUILDER.md)
    * [DS](functions/domain/DS.md)
    * ```

**Comment by fritterhoff** [comment]
Also done ;-)

**Comment by cafferata** [comment]
Thank you @fritterhoff. See the online result here: 🚀 
_<https://docs.dnscontrol.org/~/revisions/F27KYc5cDmhwljNT9zNF/language-reference/domain-modifiers/dhcid>_

**Review by cafferata — APPROVED** [review]

**Comment by tlimoncelli** [comment]
Awesome!  Thanks for following up on all this!

**Pull request merged**
