### PR TITLE
INWX: Null MX is permitted

### PR DESCRIPTION
**Pull request by tlimoncelli**
Fixes https://github.com/StackExchange/dnscontrol/issues/2643

### CODE REVIEW

**Comment by tlimoncelli** [comment]
[gvangool](https://github.com/gvangool) and @patschi: Please take a look.

**Comment by tlimoncelli** [comment]
That's an odd error message!  The type is wrong?  Maybe no field is being sent (noempty) therefore the type is not "string".

Take a look at `providers/inwx/inwxProvider.go` and add a debug printf something like...

```
  case "MX":
    req.Priority = int(rec.MxPreference)
    req.Content = content[:len(content)-1]
    printer.Printf("DEBUG: inwx mx=%q\n", req.Content)
```

That might shed some light on the situation.

**Comment by gvangool** [comment]
That gives the following (partial) log:
```
=== RUN   TestDNSProviders/phyx-ote.dev/15:MX:Null_MX
    integration_test.go:247:
        + CREATE MX phyx-ote.dev 0 . ttl=300
DEBUG: inwx mx=""
    integration_test.go:252: (2005) Parameter value syntax error. Reason: (The given parameter value for 'content' does not match the expected parameter type 'text') The given parameter value for 'content'
 does not match the expected parameter type 'text'
```

Looking at the way the trailing dot is handled for INWX, I ended up with this patch to fix it
```diff
diff --git i/providers/inwx/inwxProvider.go w/providers/inwx/inwxProvider.go
index c511d85b..23d3a233 100644
--- i/providers/inwx/inwxProvider.go
+++ w/providers/inwx/inwxProvider.go
@@ -180,7 +180,11 @@ func makeNameserverRecordRequest(domain string, rec *models.RecordConfig) *goinw
                req.Content = content[:len(content)-1]
        case "MX":
                req.Priority = int(rec.MxPreference)
-               req.Content = content[:len(content)-1]
+               if content == "." {
+                       req.Content = content
+               } else {
+                       req.Content = content[:len(content)-1]
+               }
        case "SRV":
                req.Priority = int(rec.SrvPriority)
                req.Content = fmt.Sprintf("%d %d %v", rec.SrvWeight, rec.SrvPort, content[:len(content)-1])
@@ -305,7 +309,11 @@ func (api *inwxAPI) GetZoneRecords(domain string, meta map[string]string) (model
                        "PTR":   true,
                }
                if rtypeAddDot[record.Type] {
-                       record.Content = record.Content + "."
+                       if record.Type  == "MX" && record.Content == "." {
+                               // null records don't need to be modified
+                       } else {
+                               record.Content = record.Content + "."
+                       }
                }

                rc := &models.RecordConfig{
```

**Comment by tlimoncelli** [comment]
Excellent detective work!

Would you please submit a PR?

**Pull request closed without merging**
