### PR TITLE
CLOUDFLAREAPI: Add NAPTR record support

### PR DESCRIPTION
**Pull request by asn-iac**
Add support for NAPTR records to cloudflare provider.
(#2547)

### CODE REVIEW

**Comment by asn-iac** [comment]
I added a new type to handle encoding/decoding of the data object for the NAPTR record to avoid type conflict with the existing "Flags" field in the generic "cfRecData" type.  Please let me know if it's preferred to handle in a different way.  TIA!

**Comment by tlimoncelli** [comment]
> I added a new type to handle encoding/decoding of the data object for the NAPTR record to avoid type conflict with the existing "Flags" field in the generic "cfRecData" type. Please let me know if it's preferred to handle in a different way. TIA!

Looks good to me!

**Comment by tlimoncelli** [comment]
This looks good.  I'll merge it soon.

I'm curious: What do you use NAPTR for?   I'm curious now popular this feature is. (I added the original NAPTR support but I haven't used it in a year or more)

**Comment by asn-iac** [comment]
> This looks good. I'll merge it soon.
> 
> I'm curious: What do you use NAPTR for? I'm curious now popular this feature is. (I added the original NAPTR support but I haven't used it in a year or more)

@tlimoncelli I'd actually not encountered this record type previously and had to go look at the rfc... it came up in a domain portfolio we have in cloudflare that I'm finally pulling into our dnscontrol ci/cd pipeline.  The team using this record develops a telephony-based app, so it wasn't too surprising in the end.  Most of the other domains we've managed over the years are more web app focused

Thanks again for all the hard work!

**Pull request merged**
