### PR TITLE
maint: Update GoReleaser and CircleCI configs to publish multi-arch Docker image

### PR DESCRIPTION
**Pull request by cdhunt**
This PR resolves a number of CircleCI Pipeline issues.

- Improve the filtering for the `release` job only on tag creation.
- Removes the dependency on `integration-tests` job from the `release` job. The flaky tests were frequently blocking the release.
  - Integration tests will now only run on PRs.
- Restores the Docker build/publish
  - Includes amd64, arm64, and i386 multi-arch manifest
- Uploads [artifacts](https://app.circleci.com/pipelines/github/StackExchange/dnscontrol/1285/workflows/b40ce89b-5a60-4ed2-874b-d47f383122b2/jobs/10051/artifacts) to CircleCI
- Fixes linting issues with README
- Add [CircleCI Insights badge](https://github.com/StackExchange/dnscontrol/tree/fix/cci#dnscontrol) to README
- Uploads deb and rpm packages to [CloudSmith](https://cloudsmith.io/~stackoverflow/repos/dnscontrol/packages/)
  - TODO: It looks like CloudSmith treats both format as duplicates and appends a `-1` to the version.
  - TODO: Push the Docker images to CloudSmith as well (alternate to Docker Hub and their aggressive rate limits).
- TODO: The automated release notes regex patterns don't work for most of the commits. See [releases/tag/v3.18.2-pre013](https://github.com/StackExchange/dnscontrol/releases/tag/v3.18.2-pre013)

### CODE REVIEW

**Comment by tlimoncelli** [comment]
CC @cafferata

**Comment by cdhunt** [comment]
Test the multi-arch manifest:

```shell
docker run --rm -it stackexchange/dnscontrol:v3.18.2-pre005 version
```

**Comment by jauderho** [comment]
One item that is unclear to me is that it looks like GoReleaser is used to create the binaries but not the Docker images. Given that it can do both and that there is evidence this was the case at one point, is there a reason not to do so?

**Comment by cdhunt** [comment]
@jauderho It is building all artifacts including the docker images in this branch.

**Review by tlimoncelli — APPROVED** [review]
Wow!  So much goodness in here!

**Comment by tlimoncelli** [comment]
(I'll let you do the merge)

**Comment by cdhunt** [comment]
@jauderho I guess more specifically, it is basically just invoking `docker buildx build -f Dockerfile .` We still need a `Dockerfile` and instaed rebuilding everything in the `docker build` I just copy in the binaries that gorelease spits out. I _think_ Goreaser does some magic to put the version of `dnscontrol` matching the arch in the root of `dist`. I need to get a colleague to test on an M1 Mac.

**Pull request merged**
