### PR TITLE
HEDNS: Add full Diff2 support

### PR DESCRIPTION
**Pull request by rblenkinsopp**
This adds full support for Diff2 rather than using the compatibility mode, as well as some refactoring to reduce code reuse.

It has been tested in both Diff1 and Diff2 modes and all tests pass.

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Excellent!  Thank you so much! (and congrats on a merge with no comments!)

**Comment by rblenkinsopp** [comment]
Did you mean to close this rather than merge? (No worries if you did but, it wasn't what I was expecting based on the comment :) )

**Comment by tlimoncelli** [comment]
Oops!  I totally meant to merge.

**Comment by tlimoncelli** [comment]
My apologies!

**Pull request merged**
