### PR TITLE
NAMEDOTCOM: BUGFIX: TXT records add unneeded quotes

### PR DESCRIPTION
**Pull request by tlimoncelli**
Fixes https://github.com/StackExchange/dnscontrol/issues/3259

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Gladly!

If you are on a Mac, Linux, or WIndows host, you'll need to install Git and Go.  Git has different install instructions for different OSs.   Go is on https://go.dev/ 

cd to somewhere like /tmp or an otherwise unused directory.

```
git clone https://github.com/StackExchange/dnscontrol.git
cd dnscontrol
git checkout tlim_namedotcom
go install
```

The last command (go install) will install the dnscontrol binary in your $HOME/bin directory.  You should be able to run it by just running "dnscontrol".

Change to the directory with your dnsconfig.js file and run it as normal.

Feel free to ping me with any questions!

**Comment by tkurki** [comment]
Was hoping for a one command docker based build, as I prefer not to taint my host with one time use tools. But thanks, I’ll figure that part out myself if i get around to it.

**Comment by tlimoncelli** [comment]
A docker-based build would be excellent. Sadly, we're not there yet.  (CC @cafferata )

**Comment by rmc47** [comment]
@tkurki while testing #3227, I ran the tests within a Docker container - `docker run -it golang` grabs the base Go container and pops you into an interactive shell within that environment, then you can run Tom's suggested commands within that.

**Comment by tkurki** [comment]
The changes work: with these changes dnscontrol correctly updated an existing record that had unneeded quotes and created from a scratch the original problematic record in #3259.

Thank you for looking into this so quickly.

**Comment by tlimoncelli** [comment]
Glad it worked!  I'll include this change in the next release, due in early January.

**Pull request merged**
