### PR TITLE
WIP: Add basic alidns provider (Alibaba Cloud DNS)

### PR DESCRIPTION
**Pull request by timonwong**
TODO:
- [x] REDIRECT_URL (302 redirect) & FORWARD_URL (iframe)
- [x] Basic documentation
- [ ] Tests
- [ ] "Geo" DNS
- [ ] Weighted round roubin (https://www.alibabacloud.com/help/doc-detail/60182.htm)

Limitation:
The "geodns" feature actually does not work, for example:

```js
// The following won't work because checkDuplicates does not respect provider specific metadata:
// A test-geo 1.1.1.1 -- ✅
// A test-geo 1.1.1.2 -- ❌ (duplicates)
// A test-geo 1.1.1.2 -- ❌(duplicates)
D("example.com", REG_NONE, DnsProvider(ALIDNS),
    A("test-geo", "1.1.1.1", {"alidns_line": "default"}),    // The default path
    A("test-geo", "1.1.1.2", {"alidns_line": "os_asia_sg"}),   // Singapore
    A("test-geo", "1.1.1.2", {"alidns_line": "os_asia_hk"})   // Hongkong
)
```

Any ideas?

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Looks good so far!  Thanks for working on this!

**Comment by captncraig** [comment]
Yeah, that duplicate check doesn't provide any good way to allow what you are trying to do with geo. It definitely should. I think some things need to be rethought on that front. The underlying diff algotithm can handle it, but not the preprocessing phase.

**Comment by timonwong** [comment]
> Yeah, that duplicate check doesn't provide any good way to allow what you are trying to do with geo. It definitely should. I think some things need to be rethought on that front. The underlying diff algotithm can handle it, but not the preprocessing phase.

Yes, after some digging (differences between ns1, constellix, etc), I think the opinionated way defined in [octodns](https://github.com/github/octodns/blob/master/docs/dynamic_records.md#an-annotated-example) is a good start.

Another question: Can we standardize the vendor-specific redirect records? (URL, URL301, FRAME, CF_TEMP_REDIRECT, CF_REDIRECT, and now with REDIRECT_URL and FORWARD_URL..) #455

**Comment by tlimoncelli** [comment]
Any news?

**Comment by tlimoncelli** [comment]
Closing due to age.  Please re-open if you would like to continue.

**Pull request closed without merging**
