### PR TITLE
MAINT: Refactor auditrecords.go to loop only once #1570

### PR DESCRIPTION
**Pull request by tlimoncelli**
Fixes https://github.com/StackExchange/dnscontrol/issues/1570

The old AuditRecord does a lot of unneeded work.  It loops through every record once for each test.  This change loops through all the records once, calling checking functions appropriate to that record type.  It also makes the format of the initializers readable.

I timed it on a small dataset and got a 1-3% improvement in total run time, I suspect that if I timed the function itself it would be more for providers that have many tests.

### CODE REVIEW

**Comment by tlimoncelli** [comment]
@tresni @pragmaton @mikenz @Deraen @onlyhavecans @vojtad @papakai @svenpeter42 @tlimoncelli @kordianbruck  @costasd @mistererwin  @pgaskin

Hey folks!  I rewrote the record audit stuff to be significantly faster and less verbose.  I believe I've converted the old code properly.  Please take a look.

**Review by costasd — APPROVED** [review]
LGTM for NS1

**Comment by MisterErwin** [comment]
LGTM for the rwth provider (although it is a blatant copy of the other providers)

**Comment by tlimoncelli** [comment]
Flakey tests.  They passed other times.

**Pull request merged**
