### PR TITLE
LOC: Refine which providers support it

### PR DESCRIPTION
**Pull request by tlimoncelli**
Hey @systemcrash  !

Sadly LOC was broken for some providers.  I should have done more testing before I merged the PR.

In this PR I fix the providers that I can, and I disable it for providers that weren't mentioned as definitely tested, or that I could test myself.

The individual provider maintainers can turn it on as they test it.

### CODE REVIEW

**Comment by systemcrash** [comment]
Ah, I see - sorry. I interpreted "enable for other providers" as marking whether they support it. Now I understand `Unimplemented` :)

**Comment by tlimoncelli** [comment]
Yes, they'd need to specifically enable it, test it, and then only merge it if the tests pass (or they can fix the broken tests).

I'd like to do a release tonight.  I'm going to mark them as Unimplemented unless I've tested it (or loopia, which you've tested). Are there any others that you tested?

**Comment by systemcrash** [comment]
Concretely, Loopia. I just remembered that I have a hedns account somewhere that I can try out, which I'm doing now.

**Comment by systemcrash** [comment]
I can confirm that it works with HE.net

**Comment by tlimoncelli** [comment]
> Could take a while :p

Yes, but you could ping the owners if you feel its important.

**Comment by tlimoncelli** [comment]
Sorry but I have limited time tonight.  I'm going to start the release build process.  If hedns supports LOC, please put it in a separate PR.  I'll merge it in the next release.

**Comment by systemcrash** [comment]
> I can confirm that it works with HE.net

```text
******************** Domain: example.com
6 corrections (hedns)
#1: + CREATE LOC example.com 42 21 54.000 N 71 06 18.000 W -24m 30m 1m 0.00m ttl=3600
SUCCESS!
#2: ± MODIFY NS example.com: (ns1.he.net ttl=86400) -> (ns1.he.net. ttl=86400)
SUCCESS!
#3: ± MODIFY NS example.com: (ns2.he.net ttl=86400) -> (ns2.he.net. ttl=86400)
SUCCESS!
#4: ± MODIFY NS example.com: (ns3.he.net ttl=86400) -> (ns3.he.net. ttl=86400)
SUCCESS!
#5: ± MODIFY NS example.com: (ns4.he.net ttl=86400) -> (ns4.he.net. ttl=86400)
SUCCESS!
#6: ± MODIFY NS example.com: (ns5.he.net ttl=86400) -> (ns5.he.net. ttl=86400)
SUCCESS!
Done. 6 corrections.
```
loc

**Comment by tlimoncelli** [comment]
Hey that's great!

**Comment by systemcrash** [comment]
> Hey that's great!

Actually, it was! They're like eleventybillion times faster than 💩

**Pull request merged**
