### PR TITLE
updating getting started doc for multiple providers

### PR DESCRIPTION
**Pull request by tiernano**
tweaking the Getting Started doc for multiple providers.

### CODE REVIEW

**Comment by captncraig** [comment]
I'm not sure this is perfectly clear. 'name' is not very descriptive, and it is not used in the dnsconfig anywhere, so it is not clear what this new provider is doing there. 

I would like to see maybe some comments in the js like `//define your providers here`, `//now make a domain`, and so forth. The creds.json can similarly have comments in it.

**Comment by tiernano** [comment]
thanks @captncraig. updated the naming and added some comments... hopefully it works!

**Comment by tlimoncelli** [comment]
I just did a big rewrite of that file. I didn't add this kind of info specifically as I'm not sure if it would best first there or in nameservers.md.

**Comment by tiernano** [comment]
@tlimoncelli I have updated my pull request with the document. Given that it is for multiple providers, not just DNS providers, but also registrars, leaving it where it is might be best...

**Comment by tlimoncelli** [comment]
Thanks for the PR!

**Pull request merged**
