### PR TITLE
Update helpers.js CAA_CRITICAL flag=128 (#318)

### PR DESCRIPTION
**Pull request by ismaelperal**
CAA flag "Issuer Critical Flag" sets first bit (bit 0) to 1 where bit 0 is the 8th bit in the flag, so it's doing the change by left shift 7 positions the value 1.

#318 - RFC [6844](https://tools.ietf.org/html/rfc6844#section-5.1)

### CODE REVIEW

**Comment by captncraig** [comment]
It seems there is a test failing. The value in https://github.com/StackExchange/dnscontrol/blob/master/pkg/js/parse_tests/014-caa.json needs to be updated.

**Comment by ismaelperal** [comment]
@captncraig thanks, I wasn't aware of this tests. I've updated it.

Now I don't know the reason why it's failing:

after -> go run build/validate/validate.go
"ERROR: The following files are modified after go generate:
pkg/js/static.go"

Did I miss something else?

Thank you!

**Comment by tlimoncelli** [comment]
That  just means  you need to  run "go generate".   Any changes to helpers.js require a run of "go generate"  to embed helpers.js in the binary.

**Comment by tlimoncelli** [comment]
By the way... I don't use CAA (yet) so when I created the integration tests, I was just guessing about what would be important. If you could look at https://github.com/StackExchange/dnscontrol/blob/master/integrationTest/integration_test.go#L410 and suggest improvements, please let fee free to  add/change them.

**Comment by ismaelperal** [comment]
@tlimoncelli Thanks, I will!

I think something is wrong in my development environment, sorry for the inconvenience and thanks for your help

**Comment by tlimoncelli** [comment]
I think you'll be fine if you rebase then to "go generate".  Let me know if you need assistance.

**Pull request merged**
