### PR TITLE
Docs: Fixed step number in `writing-providers`

### PR DESCRIPTION
**Pull request by riku22**
Fixed `Step 9` being duplicated in the step number in the `writing-providers` heading.

### CODE REVIEW

**Review by cafferata — APPROVED** [review]
Thanks!

**Comment by tlimoncelli** [comment]
```
4. Verify you're using the most recent version of anything you import.  (See [Step 13](#step-11-dependencies))
```

That's now Step 12.  The link should be updated too.

**Comment by riku22** [comment]
Oh, sorry.
Fixed.

**Review by tlimoncelli — APPROVED** [review]

**Comment by tlimoncelli** [comment]
Thanks!  I appreciate you noticing this and sending a PR!

**Pull request merged**
