### PR TITLE
AKAMAIEDGEDNS: new maintainer: Chris Dornin

### PR DESCRIPTION
**Pull request by svernick**
AKAMAIEDGEDNS has a new maintainer: Chris Dornin (cdornin)

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Welcome, @cdornin!  It's great to have support for this provider come directly from the vendor!

**Comment by imlonghao** [comment]
It seems too late for me to say, but the GitHub id cdornin doesn't even exist...

**Comment by tlimoncelli** [comment]
Oops!  It looks like I merged this too soon.  [svernick](https://github.com/svernick), do you have Chris' github account name?

**Comment by svernick** [comment]
My mistake!  I jumped the gun.  Sincere apologies!

Chris will create the account later today.

From: Tom Limoncelli ***@***.***>
Reply-To: StackExchange/dnscontrol ***@***.***>
Date: Wednesday, May 8, 2024 at 10:25 AM
To: StackExchange/dnscontrol ***@***.***>
Cc: "Vernick, Steve" ***@***.***>, Author ***@***.***>
Subject: Re: [StackExchange/dnscontrol] AKAMAIEDGEDNS: new maintainer: Chris Dornin (PR #2940)


Oops! It looks like I merged this too soon. svernick<https://urldefense.com/v3/__https:/github.com/svernick__;!!GjvTz_vk!S-pnf_xN5IQDMi9L8d7UJYylVNF_3KG1DQMeUmyRgd2qNQGxCCMQ8dUdLYy3oNZmu2GHFP6ZNsHBbT725xJsKaU$>, do you have Chris' github account name?

**Pull request merged**
