### PR TITLE
NS1: Added support for ALIAS, PTR, and TXTMulti

### PR DESCRIPTION
**Pull request by MaxRatmeyer**
#775 Adds support for ALIAS records and enables PTR and TXTMulti.

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Looks great!  Can you paste in the complete integration test output? Thanks!

**Comment by MaxRatmeyer** [comment]
Sure, https://pastebin.com/dDZx50tn. It looks like it's still failing a few of the tests that it failed when I tested this morning but the changes should be all clear. Thanks

**Comment by tlimoncelli** [comment]
Ok.  I've filed those bugs as https://github.com/StackExchange/dnscontrol/issues/779

Congrats on the merger of your first PR!  Oh, and I believe you are the youngest to contribute to the project. Double congrats!

**Comment by MaxRatmeyer** [comment]
Awesome, thanks so much for your help!

**Pull request merged**
