### PR TITLE
Switch to official Vultr API library

### LINKED ISSUE #528: Switch to official Vultr API library
Vultr just released an official API library: [github.com/vultr/govultr](https://godoc.org/github.com/vultr/govultr). I might work on this if I have time.

Edit: Also add support for SSHFP records.

### PR DESCRIPTION
**Pull request by geek1011**
This PR switches to the new official Vultr API library and does a bit of cleanup on the provider code.

closes #528

### CODE REVIEW

**Comment by geek1011** [comment]
**Important:** Don't merge this for now, I've found some serious issues in govultr (it will panic randomly).

**Comment by geek1011** [comment]
This is now ready to be merged.

**Comment by captncraig** [comment]
Wonderful!

Ive been working on making more of the integration tests runnable from a
public azure pipelines setup. Is there an easy way to get free credendtials
that can be used to run vultr in the official integration test suite?

Ive found that providers we are not actively checking tend to break over
time.

**Comment by geek1011** [comment]
Yep. You can create an account (although it needs a card to verify) and use the DNS for free. Note that the API key has access to billing, but you can restrict it to specific IP ranges.

**Comment by captncraig** [comment]
Passed Integration tests. LGTM. Thank you!

**Pull request merged**
