### PR TITLE
Add Dependabot and CodeQL scanning

### PR DESCRIPTION
**Pull request by jauderho**
This helps keeps dependencies up to date as well as identify any potential code issues.

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Looking good so far!

Our automated testing only covers certain providers (R53, GCP, etc).  Dependencies for those should be automatically updated because the tests will find any breakage.  However other providers (namecheap, dnsimple, egoscale, ovh, softlayer, govultr, ns1) we don't have automated tests and therefore those dependencies shouldn't be updated except by the community maintainer.

Is there a way to accommodate this situation?

Tom

**Comment by jauderho** [comment]
I think it may be possible after looking at the documentation

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#configuration-options-for-updates

If you have a list that you want ignored, I believe adding the ignore param should accomplish what you are looking for.

Additionally, the CodeQL scan appears to have identified a number of type mismatches.

**Comment by tlimoncelli** [comment]
Where do I see the CodeQL results?  I see it mentions "Uploading results" but not where they are sent.

**Comment by tlimoncelli** [comment]
Awesome!  Could you add these to the ignore-list?

```
github.com/billputer/go-namecheap
github.com/dnsimple/dnsimple-go
github.com/exoscale/egoscale
github.com/ovh/go-ovh
github.com/softlayer/softlayer-go
github.com/vultr/govultr
gopkg.in/ns1/ns1-go.v2
```

**Comment by tlimoncelli** [comment]
Looks good!

1) I fixed all but 2 of the errors.  Those 2 will be fixed in https://github.com/StackExchange/dnscontrol/pull/1181.  Do you want me to delay merging that so you have some results to view?

2) This looks good so far.  Let me know when it is ready to merge. 

Thanks!

**Comment by jauderho** [comment]
Sorry for the delay but if you are comfortable with merging as-is, I can test and submit a separate pull request later once I figure out how the ignore keyword works.

**Comment by tlimoncelli** [comment]
Merging now...

FYI: The javascript codeql takes a long time.  It is auto-generated code, so I don't know if testing it is worthwhile.  Something to consider!

**Comment by tlimoncelli** [comment]
More info... the `docs/flattener/flattener.js` file is 7.1M.  We should skip it as processing it takes a long long time. It is auto-generated and won't change.

**Comment by jauderho** [comment]
Submitted pull request for Dependabot ignores. I'll look at the javascript ignore later.

**Pull request merged**
