### PR TITLE
HEDNS: Re-enable CI integration tests

### PR DESCRIPTION
**Pull request by rblenkinsopp**
This re-enables the CI integrations test now that CircleCI is used for CI testing.

### CODE REVIEW

**Comment by rblenkinsopp** [comment]
@tlimoncelli Is there any documentation for the bring your own secrets integration tests now you've moved to CircleCI? The documentation still references the old flow and I'm unsure how to rename with CircleCI as I'm unfamiliar with it.

**Comment by tlimoncelli** [comment]
This would be a good time to document the steps!  I'll add them to release-engineering.md once we figure out the steps.

I just went through the steps and documented them in https://github.com/StackExchange/dnscontrol/pull/1927

Sadly I have a free account and the CCI config currently specs `resource_class: 2xlarge` which isn't available to free accounts.

Do you have a paid CCI?  I'd consider changing the config.yml file to large and see if that works.

**Comment by tlimoncelli** [comment]
This is marked as a draft. Please let me know if there's anything I can do to help!

**Comment by rblenkinsopp** [comment]
It needs a bit of clean-up and I was waiting to see if there was a resolution to https://github.com/StackExchange/dnscontrol/issues/1935 as you might notice the current changelog has `2xlarge` -> `large` change in it :). That said there is no reason for this to have to wait until then, I could get it merged, but the value is less if I have to make  `2xlarge` -> `large` on every branch to get the value from integration tests.

**Comment by tlimoncelli** [comment]
It will take a few days to complete #1935 due to other priorities.  However it will get fixed.

I propose we merge this so at least you're unblocked.  You'll only have to locally edit config.yml for a short amount of time.

**Comment by tlimoncelli** [comment]
This is marked as a draft. Anything I can do to help out?

**Comment by rblenkinsopp** [comment]
I think this is good to be merged, apologies for leaving it languishing until now.

**Comment by rblenkinsopp** [comment]
Sent. I originally thought this was to enable the "Bring your own secrets" workflow rather than the main CI but since it's a dummy account, I'm very happy for it to be added with the secrets :)

**Comment by tlimoncelli** [comment]
Oh yeah!  I forgot this was a BYO-secrets situation.  It shouldn't have failed.  I'll fix that first.  

But thank you for the creds.  I'll integrate them next!

**Comment by rblenkinsopp** [comment]
> Oh yeah! I forgot this was a BYO-secrets situation. It shouldn't have failed. I'll fix that first.

It might have failed due to the `2xlarge` not on free accounts issue? I'm happy for it to be integrated, I didn't know that giving you the creds to do that was an option until now. It's probably better than a BYO secrets solution which only works on MRs?

**Comment by tlimoncelli** [comment]
@rblenkinsopp Looks like its working!  Thanks for sending the demo creds.   Now you won't get nag messages from me asking to run tests manually! 

https://app.circleci.com/pipelines/github/StackExchange/dnscontrol/3021/workflows/5b37e4e8-2ce6-44da-af87-a6d0106a6e5f/jobs/20667

Or the bigger picture:
https://app.circleci.com/pipelines/github/StackExchange/dnscontrol/3021/workflows/5b37e4e8-2ce6-44da-af87-a6d0106a6e5f

**Comment by tlimoncelli** [comment]
The 2xlarge issue will go away when we move (back) to GHA. In the meanwhile, you can use the suggestion in [documentation/release-engineering.md](https://docs.dnscontrol.org/developer-info/byo-secrets)

**Pull request merged**
