### PR TITLE
CLOUDFLAREAPI: Enable DNSKEY, HTTPS, SVCB record types

### LINKED ISSUE #2964: Cloudflare api for SVCB HTTPS and DNSKEY record
support cloudflare api for SVCB HTTPS and DNSKEY record please

### LINKED ISSUE #2965: require json5 file?
**Is your feature request related to a problem? Please describe.**
I want to require json5 file

**Describe the solution you'd like**
unexpected token :

**Describe alternatives you've considered**
change to json suffix can fix

### PR DESCRIPTION
**Pull request by charliez0**
Fixes #2964

### CODE REVIEW

**Comment by charliez0** [comment]
@tlimoncelli

**Comment by tlimoncelli** [comment]
Looks good!  Thanks for contributing this!

**Comment by tlimoncelli** [comment]
Somehow I missed that one test failed:

```
tlimwork6:~/git/dnscontrol/integrationTest$ go test -v -verbose -provider CLOUDFLAREAPI -start 47 -end 47
=== RUN   TestDNSProviders
=== RUN   TestDNSProviders/dnscontroltest-cf.com
=== RUN   TestDNSProviders/dnscontroltest-cf.com/Clean_Slate:Empty
    integration_test.go:236: 
        - DELETE final.dnscontroltest-cf.com TXT "TestDNSProviders was successful!" ttl=1 id=d15065610be06f30493e7e8b1688d44d
=== RUN   TestDNSProviders/dnscontroltest-cf.com/47:DNSKEY:Create_DNSKEY_record
    integration_test.go:236: 
        + CREATE test.dnscontroltest-cf.com DNSKEY 257 3 13 fRnjbeUVyKvz1bDx2lPmu3KY1k64T358t8kP6Hjveos= ttl=1
    integration_test.go:241: DNS Validation Error (1004)
--- FAIL: TestDNSProviders (5.08s)
    --- FAIL: TestDNSProviders/dnscontroltest-cf.com (2.40s)
        --- PASS: TestDNSProviders/dnscontroltest-cf.com/Clean_Slate:Empty (1.15s)
        --- FAIL: TestDNSProviders/dnscontroltest-cf.com/47:DNSKEY:Create_DNSKEY_record (1.08s)
=== RUN   TestDualProviders
    integration_test.go:337: Skipping.  DocDualHost == Cannot
--- SKIP: TestDualProviders (1.64s)
=== RUN   TestNameserverDots
    integration_test.go:401: Skipping.  DocDualHost == Cannot
--- SKIP: TestNameserverDots (1.78s)
FAIL
exit status 1
FAIL	github.com/StackExchange/dnscontrol/v4/integrationTest	9.270s
```

Since Cloudflare is reporting this as a validating error, maybe the problem is that the test data isn't a valid DNSKEY?

I don't know much about DNSKEY. Can you check the tests to see if they are valid?  If possible, enter similar records using cloudflare's web control panel and see if they are accepted there.  https://github.com/StackExchange/dnscontrol/blob/68b0b300d61cc23fee7f483426d23e45aee1d89b/integrationTest/integration_test.go#L1654

CC @tresni 
CC @charliez0 

NOte t

**Comment by charliez0** [comment]
cloudflare can only add dnskey record on apex only with multi sign enabled, so it's expected to fail.

**Comment by charliez0** [comment]
cloudflare can only add dnskey record on apex only with multi sign enabled, so it's expected to fail.

**Comment by tlimoncelli** [comment]
Ah!  Thank you for the explanation! 

I don't know much about GPG. Can we use test data that is multi sign?

Or should we have 2 tests (apex and non-apex)?

**Comment by charliez0** [comment]
> Ah! Thank you for the explanation!
> 
> I don't know much about GPG. Can we use test data that is multi sign?
> 
> Or should we have 2 tests (apex and non-apex)?

We may need 2 tests as others may support that, also you need to turn on multi signing on the cloudflare zone's settings, or another error would issue

**Comment by charliez0** [comment]
Cloudflare only verify whether the data is base64

**Pull request merged**
