### PR TITLE
Remove value check for removed AUTODNSSEC() function (we now only have AUTODNSSEC_ON and AUTODNSSEC_OFF)

### PR DESCRIPTION
**Pull request by Yannik**
(Not removing the function due to #2090)

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Which should I merge first?  This or https://github.com/StackExchange/dnscontrol/pull/2090 ?

**Comment by Yannik** [comment]
I guess #2090

**Comment by tlimoncelli** [comment]
Please rebase

**Comment by Yannik** [comment]
@tlimoncelli done

**Pull request merged**
