### PR TITLE
CHORE: Resolved unused parameter warnings

### PR DESCRIPTION
**Pull request by tlimoncelli**
Fixed many linting errors all related to "unused parameters".  There are still some left to fix.

CC'ing various code owners for visibility:

* pkg/normalize @tlimoncelli
* providers/akamaiedgedns @svernick
* providers/azuredns @vatsalyagoel
* providers/azureprivatedns @matthewmgamble
* providers/cscglobal @mikenz
* providers/desec @D3luxee
* providers/digitalocean @Deraen
* providers/dnsmadeeasy @vojtad
* providers/doh @mikenz
* providers/hexonet @KaiSchwarz-cnic
* providers/hostingde @juliusrickert
* providers/oracle @kallsyms
* providers/packetframe @hamptonmoore
* providers/rwth @mistererwin
* providers/vultr @pgaskin

### CODE REVIEW

**Comment by tlimoncelli** [comment]
FYI: I'm not "squashing" these so that they can be reverted individually if needed.

**Comment by KaiSchwarz-cnic** [comment]
Looking good @tlimoncelli . Thanks so much 👍

**Comment by juliusrickert** [comment]
I can't test the change for `HOSTINGDE` at the moment. But it's a dead code path and shouldn't affect its behaviour, right?

**Comment by tlimoncelli** [comment]
> I can't test the change for `HOSTINGDE` at the moment. But it's a dead code path and shouldn't affect its behaviour, right?

That's the theory!  :-)   (I put each provider in a different commit to make it easy to revert if there are problems later)

**Pull request merged**
