### PR TITLE
Update TXT handling for DNSimple

### PR DESCRIPTION
**Pull request by tlimoncelli**
@aeden please run the integration tests and verify I didn't break anything.

### CODE REVIEW

**Comment by aeden** [comment]
@onlyhavecans can you please take a look at this when you have a moment. Thanks!

**Comment by onlyhavecans** [comment]
DNSimple is currently failing on the following tests with a validation failure from our system. However, I checked and see these exact same failures in the main branch. I will address these in another PR


complex_TXT:Create_TXT_with_double-quote
CAA_Issue_1374:CAA_spaces
DS:DS_create

**Comment by onlyhavecans** [comment]
Now that we have all the tests in the main branch working, if you want to rebase/merge those into this I can test this directly.

**Comment by tlimoncelli** [comment]
Rebased and ready to test again.

**Comment by onlyhavecans** [comment]
Sorry, I don't see the changes from `master` in this branch, and the same tests fail

**Comment by tlimoncelli** [comment]
I'll be closing this without merging it. See https://github.com/StackExchange/dnscontrol/pull/1567#issuecomment-1184697723 for an explanation.  I do ask that all provider maintainers do 2 things:
1.  Check out the master branch and re-run the integration tests (dnscontrol/integrationTest). (Its a good idea to do this once a year just in case)
2. check your provider to make sure the TXT bug doesn't exist: https://stackexchange.github.io/dnscontrol/testing-txt-records.html

Thanks for the effort so far and, again, my apologies for asking you to do work that later got tossed.  If there are things you'd like to salvage from this PR, please submit the changes as a PR against master.

**Pull request closed without merging**
