### PR TITLE
CHORE: Remediate staticcheck warnings

### PR DESCRIPTION
**Pull request by tlimoncelli**
Problem:

staticcheck reports these issues:

```
pkg/js/hash.go:20:2: this value of result is never used (SA4006)
providers/autodns/autoDnsProvider.go:101:14: printf-style function with dynamic format string and no further arguments should use print-style function instead (SA1006)
providers/dnsimple/dnsimpleProvider.go:732:9: printf-style function with dynamic format string and no further arguments should use print-style function instead (SA1006)
providers/hedns/hednsProvider.go:693:9: printf-style function with dynamic format string and no further arguments should use print-style function instead (SA1006)
providers/oracle/oracleProvider.go:180:16: error strings should not be capitalized (ST1005)
providers/oracle/oracleProvider.go:180:16: error strings should not end with punctuation or newlines (ST1005)
```

golint reports:
```
providers/cnr/cnrProvider.go:1:1: package comment should be of the form "Package cnr ..."
providers/porkbun/api.go:89:3: should replace retrycnt += 1 with retrycnt++
```

Solution:

Fix them.

### CODE REVIEW

**Comment by tlimoncelli** [comment]
CC @arnoschoon @onlyhavecans @rblenkinsopp @kallsyms for visibility.

**Comment by tlimoncelli** [comment]
CC @AsifNawaz-cnic @KaiSchwarz-cnic for visibility

**Comment by KaiSchwarz-cnic** [comment]
@tlimoncelli my pardon if checks failed - I was playing with integration tests in parallel and missed using a different test domain and by that we both run into collisions. I'll switch our side now to something different.

**Comment by tlimoncelli** [comment]
@KaiSchwarz-cnic Colliding over the same domain is great news!  I was worried it was something deeper!  What a relief!

I'll merge this and that should take care of the issues staticcheck listed for CNR.

**Pull request merged**
