### PR TITLE
HEXONET: Adopt diff2 in compatibility mode

### PR DESCRIPTION
**Pull request by tlimoncelli**
Hi @papakai:

In reference to replacing pkg/diff with the new pkg/diff2 (https://github.com/StackExchange/dnscontrol/issues/1854)

I've introduced a compatibility mode to pkg/diff2 to make it easier for providers to adopt the new system.  If you do a diff with "hide whitespace", you'll see the changes are minimal.

I've taken the liberty of providing this PR as a starting point.

Please run the integration tests and let me know the result. (If you're getting this, I probably don't have access to an account on this provider)

Please run:
```
    go test -v -verbose -provider HEXONET
```
and
```
    go test -v -verbose -provider HEXONET -diff2
```

They should both complete with no failures. Please fix any failures or loop me in for help.

If you are interested in porting to the new pkg/diff2/By*() functions, I'd be glad to accept a PR. However using the compatibility mode is sufficient if all tests pass.

Thanks and happy new years!!!

Tom
@tlimoncelli

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Friendly ping? @papakai

**Comment by KaiSchwarz-cnic** [comment]
@tlimoncelli phew... how could I've missed your mentionings? By accident I stumbled over this PR (release Notes of v3.25.0).
I'll follow-up asap!

**Comment by KaiSchwarz-cnic** [comment]
@tlimoncelli not sure what I am exactly missing ...

So, what I did - I rebased our fork of dnscontrol to upstream master, then checked out a new branch and reset it to this branch.
When running the commands I always run into:

image

Probably just a little step is missing on our end :-)

**Comment by tlimoncelli** [comment]
P.S. Some environment variables need to be set too.

Set $HEXONET_DOMAIN to the test domain (note: this will delete all the records there. Use a throw-away domain.)

One or more of these need to be set for authentication purposes:

$HEXONET_ENTITY
$HEXONET_UID
$HEXONET_PW
$HEXONET_DEBUGMODE
$HEXONET_IP

**Comment by KaiSchwarz-cnic** [comment]
My gh account got renamed to KaiSchwarz-cnic and someone else created a new account with my old account name.... that's why I didn't receive notifications. 🫥

**Comment by tlimoncelli** [comment]
Wow!  Modern problems, eh?   LOL

**Comment by tlimoncelli** [comment]
Ok, now that we've solved those problems... do the tests work?

Reviewing all the comments... these are the steps:

```
export HEXONET_DOMAIN="INSERT_TEST_DOMAIN"
export HEXONET... (any other variables needed)
cd integrationTests && go test -v -verbose -provider HEXONET -diff2
```

**Comment by KaiSchwarz-cnic** [comment]
All tests finished smoothly, without `-diff2` and with `-diff2` parameter.
We've now also our development process back in place for dnscontrol based on a docker image. Let me again forward a "thank you" for all the help we received by you and your team over the last year.

**Comment by tlimoncelli** [comment]
Thanks for the confirmation on the tests!  I'll merge soon.

Thank you for the thank you! ;-)

**Pull request merged**
