### PR TITLE
Add list-unmanaged command (#1976)

### PR DESCRIPTION
**Pull request by Yannik**
This PR adds a `list-unmanaged` command, which allows listing unmanaged domains and zones. For domains, a `ListDomains` interface has been added, which is similar to `ListZones`. I have additionally supplied a reference implementation for the hosting.de provider.

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Is the goal for this to only apply to domains?

(A domain is what you register (example.com).  A zone is either a domain or a subdomain (subdomain.example.com).)

**Comment by Yannik** [comment]
> Is the goal for this to only apply to domains?
> 
> (A domain is what you register (example.com). A zone is either a domain or a subdomain (subdomain.example.com).)

@tlimoncelli 

No, it should list both unmanaged domains and unmanaged zones. Is there something wrong with my code? For me it's working as expected.

**Comment by tlimoncelli** [comment]
I guess I'm confused because I'm not sure if this command is for domains or zones. Or both? I would prefer two separate commands.

Let's take a step back and make sure we both understand what we're trying to achieve.  

Tom

P.S.  DNSControl sometimes confuses domains and zones.  A lot of code refers to a "domain name" when it is really a zone name.  For example `D()` defines a zone, not a domain. Technically it should have been `Z()`.

**Comment by Yannik** [comment]
@tlimoncelli 

I have changed the command a bit.

Now you can do 

```
dnscontrol list-unmanaged zones creds
```
to list unmanaged domains

and

```
dnscontrol list-unmanaged zones creds
```

to list unmanaged domains

Is that okay with you?

**Comment by Yannik** [comment]
@tlimoncelli 
@tlimoncelli 

I have changed the command a bit.

Now you can do 

```
dnscontrol list-unmanaged domains creds
```
to list unmanaged domains

and

```
dnscontrol list-unmanaged zones creds
```

to list unmanaged domains

Is that okay with you?

**Comment by Yannik** [comment]
@tlimoncelli 

I have changed the command a bit.

Now you can do 

```
dnscontrol list-unmanaged domains <creds>
```
to list unmanaged domains

and

```
dnscontrol list-unmanaged zones <creds>
```

to list unmanaged domains

Is that okay with you?

**Comment by Yannik** [comment]
@tlimoncelli 

I have changed the command a bit.

Now you can do 

```
dnscontrol list-unmanaged domains <creds>
```
to list unmanaged domains

and

```
dnscontrol list-unmanaged zones <creds>
```

to list unmanaged zones

Is that okay with you?

**Comment by Yannik** [comment]
@tlimoncelli 

I have changed the command a bit.

Now you can do 

```
dnscontrol list-unmanaged domains <credkey>
```
to list unmanaged domains

and

```
dnscontrol list-unmanaged zones <credkey>
```

to list unmanaged zones

Is that okay with you?

**Comment by tlimoncelli** [comment]
Yes, that's a lot better!  Thanks!

The code looks ready to merge.  Please rebase and I'll merge it.

**Comment by Yannik** [comment]
Done @tlimoncelli

**Comment by tlimoncelli** [comment]
Looks good so far!

1. Help message

The help message needs to be adjusted:

```
$ dnscontrol -h
...
...
     get-zones, get-zone  gets a zone from a provider (stand-alone)
     list-unmanaged       gets a zone from a provider (stand-alone)
```

2. Docs

 Please add a documentation page simile to https://docs.dnscontrol.org/commands/get-zones

3. Should we make this a general command?

Now that I see the command in action I wonder if what we should have is a more general command:

```
dnscontrol list [zones|domains] [--unmanaged]
```

Or maybe split it out?

```
dnscontrol list-zones [--unmanaged]
dnscontrol list-domains [--unmanaged]
```

Tom

**Comment by Yannik** [comment]
@tlimoncelli 

Regarding 1  and 2: I will take care of it tomorrow.

Regarding 3: `dnscontrol list [zones|domains] [--unmanaged]` It is unclear to me whether it should return the candidate config (domains/zones as configured in dnscontrol), or the running config (domains/zones as currently deployed) when called without the `--unmanaged` flag. Splitting it into `list-zones` and `list-domains` is fine with me.

Additionally: I'd like to wait for your feedback on #2050 before we make this final so we have a similar user experience for both listing unmanaged zones and previewing/pushing them. (Now that I'm thinking about it: do we even need this command if we can see unmanaged zones using `preview`?)

**Comment by tlimoncelli** [comment]
My feedback on https://github.com/StackExchange/dnscontrol/pull/2050 is: GREAT!  Yes, let's do that!

Whether we also need the commands is up to you. If https://github.com/StackExchange/dnscontrol/pull/2050 is sufficient for now, we could take some time and decide what the command names and flags should be.

For example, if we had more time, I'd recommend we make a general system:  There are 3 sources: (1) zones listed in dnsconfig.js, (2) ListZones(), (3) ListDomains().  There are 3 modifiers: all/managed/unmanaged.  There are different actions to take: print, delete.  That's 18 combinations (not all valid).  Obviously we don't want 18 new subcommands.

Tom

**Comment by Yannik** [comment]
> Whether we also need the commands is up to you. If https://github.com/StackExchange/dnscontrol/pull/2050 is sufficient for now, we could take some time and decide what the command names and flags should be.

I think it's fine to shelve this for now. Let's revisit it after finishing #2050.

**Pull request closed without merging**
