### PR TITLE
NEW DOC: Doc Style Guide

### PR DESCRIPTION
**Pull request by tlimoncelli**
CC @cafferata 

Feedback requested.

I'm not sure if I got all of the examples correct. In fact, I'm sure I didn't because I just copied the first example I saw in existing docs and may not have stumbled upon the right one.

### CODE REVIEW

**Comment by cafferata** [comment]
What do you prefer? A GitHub pull request feedback with individual items? Or shall I provide a branch/pull request?

**Comment by tlimoncelli** [comment]
> What do you prefer? A GitHub pull request feedback with individual items? Or shall I provide a branch/pull request?

branch/pull for large changes.  Thanks!

**Comment by cafferata** [comment]
https://github.com/StackExchange/dnscontrol/pull/2383 replaces this PR.

**Comment by cafferata** [comment]
This pull request can be closed by https://github.com/StackExchange/dnscontrol/pull/2383. 🥳

**Pull request closed without merging**
