### PR TITLE
DOCS: Fixed LOC_BUILDER_STR filename

### PR DESCRIPTION
**Pull request by cafferata**
This pull request fixed the broken `LOC_BUILDER_STR({})` link on [LOC](https://docs.dnscontrol.org/language-reference/domain-modifiers/loc). https://github.com/StackExchange/dnscontrol/pull/2188 https://github.com/StackExchange/dnscontrol/pull/2183 cc: @systemcrash

### CODE REVIEW

**Comment by systemcrash** [comment]
This and #2198 may get superseded by #2197 if #2197 gets merged. Basically all docs get restructured. Then these would apply better. 

I think I missed a few things in the docs adding LOC 😅

**Comment by cafferata** [comment]
Thanks @systemcrash for the link. 👍 I've been reading the GitHub pull request from old to new and got to https://github.com/StackExchange/dnscontrol/pull/2197 😅

**Comment by tlimoncelli** [comment]
I'm fine with waiting until https://github.com/StackExchange/dnscontrol/pull/2197.

**Comment by cafferata** [comment]
Personally I would merge since the current link doesn't work.

**Pull request merged**
