### PR TITLE
Beta of creds.json "TYPE" change

### PR DESCRIPTION
**Pull request by tlimoncelli**
This PR is a proposed solution to https://github.com/StackExchange/dnscontrol/issues/1457

It should be 100% backwards compatible.

I'm asking that people test it and give feedback.

1. Build this version and run "dnscontrol preview". It should work with no changes.  (It will generate some warnings suggesting you change your config. Ignore those until the next step).
2. Follow the instructions in docs/v316.md to convert your configuration to the new style.  Did it work for you?  Do you hit any snags?  was the documentation confusing?

I'd appreciate any feedback!

I'd like to merge this on Sunday, May 8th. I know that doesn't give people a lot of time but I appreciate the help if you are able.

Thanks!
Tom

CC: @aeden @blackshadev @captncraig @costasd @D3luxee @das7pad @Deraen @hamptonmoore @hnrgrgr @jpbede @juliusrickert @kallsyms @koesie10 @kordianbruck @masterzen @mikenz @papakai @pgaskin @philhug @pragmaton @rblenkinsopp @svenpeter42 @svernick @tlimoncelli @TomOnTime @tresni @vatsalyagoel @vojtad @philpennock

### CODE REVIEW

**Comment by vatsalyagoel** [comment]
I'll review this by EOD tomorrow

**Comment by hnrgrgr** [comment]
Works great for `AXFRDDNS` with:
https://github.com/hnrgrgr/dnscontrol/commit/4454472f2aa25e2f2d19763c2f19d1b4be195a04

**Review by jpbede — APPROVED** [review]
Works great with PowerDNS. Code looks also good.

**Comment by rblenkinsopp** [comment]
Works great for `HEDNS`, Nice change :)

**Comment by tlimoncelli** [comment]
Update: I've added code to de-dup the warnings.  I had 297 warnings; 10 were unique.

**Comment by tlimoncelli** [comment]
> Works great for `HEDNS`, Nice change :)
> 
> @tlimoncelli: Are you looking for providers to submit updates to their relevant documentation pages as part of this change? (E.g: https://stackexchange.github.io/dnscontrol/providers/hedns)

You've read my mind!  Once this PR is merged, I'm going to do a round of documentation updates.  The working PR for that is here: https://github.com/StackExchange/dnscontrol/pull/1499

**Comment by costasd** [comment]
Works fine with `NS1` and `BIND` (only maintaining NS1 myself, but using both in my prod setups, so I tested both)

**Comment by tlimoncelli** [comment]
Thanks [hnrgrgr](https://github.com/hnrgrgr), [jpbede](https://github.com/jpbede), [costasd](https://github.com/costasd)!

**Comment by D3luxee** [comment]
No issues with deSEC

**Comment by patschi** [comment]
I can confirm `INWX` and `OVH` works.

Just one thing:
```
INFO: In dnsconfig.js New*("PK-INWX", "INWX") can be simplified to New*("PK-INWX") (See https://stackexchange.github.io/dnscontrol/creds-json#cleanup)
```

I don't really like those `New*` here, but honestly I don't have any better suggestions right now.

**Comment by tlimoncelli** [comment]
> I don't really like those `New*` here, but honestly I don't have any better suggestions right now.

Yeah, that's pretty gross.  I looked into it and I'm able to generate the proper function call.   I also found a situation where the warnings to to stdout instead of stderr.  (See 4fec47f96131ee4cb7215fc35cb81067a94eabb6)

Please test that out and make sure it is outputting NewRegister() and NewDnsProvider() at the right times.

**Comment by onlyhavecans** [comment]
Works great with `DNSIMPLE`

**Comment by tlimoncelli** [comment]
Thanks for checking in, [onlyhavecans](https://github.com/onlyhavecans)!

At this point I'm fairly confident about this change.  The places I could use more testing:
* Shell scripts that call `dnscontrol` subcommands like `get-zones`, `get-zone`, or `check-creds`
* Large sites with strange configurations.

**Comment by patschi** [comment]
> Please test that out and make sure it is outputting NewRegister() and NewDnsProvider() at the right times.

Just tested it with one line, and works:
```
INFO: In dnsconfig.js NewRegistrar("none", "NONE") can be simplified to NewRegistrar("none") (See https://stackexchange.github.io/dnscontrol/creds-json#cleanup)
```

Looks good.

**Comment by tresni** [comment]
Tested with `HEDNS`, `CLOUDFLAREAPI` (with redirects, but not workers), `EASYNAME`, and `LINODE`.  No issues that I saw.

**Comment by das7pad** [comment]
Manually tested with a dual-homed zone on `HETZNER` and `ROUTE53`. It works fine before and after making the changes to the creds/dnsconfig file.
Thanks for adding the `none` dummy credential, it keeps my creds file DRY :slightly_smiling_face: 

Side note: There is one unrelated failure in the integration tests for the `HETZNER` provider. Specifically in [`CAA Issue 1374 -> CAA spaces`](https://github.com/StackExchange/dnscontrol/blob/8ff96024914ccf44538d9bd32591c60ffedb828c/integrationTest/integration_test.go#L1098-L1102): Their validation is tripping over the quoted field. I'll send them an email.

**Comment by tlimoncelli** [comment]
[das7pad](https://github.com/das7pad): Thanks for the report!

**Comment by tlimoncelli** [comment]
Thanks to everyone who gave feedback!  Finally merging this!

**Comment by svenpeter42** [comment]
> Edit: @tlimoncelli Happy to be a co-maintainer for INWX, if you wish. Primarily using INWX for my domains, so I'm interested in having this working myself.

Sounds good to me, it's also fine with me if you take over maintainership completely fwiw.

**Pull request merged**
