### PR TITLE
CICD: GoReleaser version

### PR DESCRIPTION
**Pull request by cafferata**
## What is the reason for this pull request?

I saw the comment below listed in the various YAML files within `.github/workflows`. So I thought I'd see how far I could get! 🤓 

1. [.github/workflows/pr_test.yml#L41-L44](https://github.com/StackExchange/dnscontrol/blob/1bbf9c4293f6cd5127bf190ead5ed738dd11c437/.github/workflows/pr_test.yml#L41-L44)
2. [.github/workflows/release_draft.yml#L52-L55]( https://github.com/StackExchange/dnscontrol/blob/1bbf9c4293f6cd5127bf190ead5ed738dd11c437/.github/workflows/release_draft.yml#L52-L55)

```text
# For some reason goreleaser isn't correctly setting the version
# string used by "dnscontrol version".  Therefore, we're forcing the
# string using the GORELEASER_CURRENT_TAG feature.
# TODO(tlim): Use the native gorelease version mechanism.
```

## GoReleaser documentation

By default, GoReleaser will set the following 3 *ldflags*\:

1. `main.version`\: Current Git tag (the `v` prefix is stripped) or the name of the snapshot, if you're using the `--snapshot` flag
2. `main.commit`\: Current git commit SHA
3. `main.date`\: Date in the [RFC3339](https://golang.org/pkg/time/#pkg-constants) format

_https://goreleaser.com/cookbooks/using-main.version/_

**Name Templates**

1. [{{ .Version }}](https://goreleaser.com/customization/templates/#:~:text=.Version): the version being released
2. ~~[{{ .Commit }}](https://goreleaser.com/customization/templates/#:~:text=.Commit): the git commit hash (deprecated)~~
3. ~~[{{ .Date }}](https://goreleaser.com/customization/templates/#:~:text=.Date): current UTC date in RFC 3339 format~~

_https://goreleaser.com/customization/templates/_

**GitHub Actions**

_https://goreleaser.com/ci/actions/_

### GoReleaser

```shell
goreleaser build --snapshot --clean
```

<details>
    <summary>GoReleaser output</summary>

```
  • starting build...
  • loading                                          path=.goreleaser.yml
  • skipping validate...
  • loading environment variables
  • getting and validating git state
    • git state                                      commit=7bee368435c9fdd8ed8beaf6df4398fd1835cfb9 branch=cicd/goreleaser-version current_tag=v4.7.3 previous_tag=v4.7.2 dirty=true
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
  • snapshotting
    • building snapshot...                           version=4.7.4-next
  • running before hooks
    • running                                        hook=go fmt ./...
    • running                                        hook=go mod tidy
    • running                                        hook=go generate ./...
    • took: 3s
  • checking distribution directory
    • cleaning dist
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • building binaries
    • building                                       binary=dist/build_darwin_arm64/dnscontrol
    • building                                       binary=dist/build_darwin_amd64_v1/dnscontrol
    • took: 4s
  • universal binaries
    • creating from 2 binaries                       id=build binary=dist/build_darwin_all/dnscontrol
  • storing release metadata
    • writing                                        file=dist/artifacts.json
    • writing                                        file=dist/metadata.json
  • build succeeded after 7s
  • thanks for using goreleaser!
```
</details>

```shell
./dist/build_darwin_all/dnscontrol version
```

```diff
-dnscontrol "4.7.4-next" ("1bbf9c4293f6cd5127bf190ead5ed738dd11c437") built 19 Dec 23 12:28 CET
+DNSControl 4.7.4-next
```

### Go build

```shell
go build
```
```shell
./dnscontrol version
```

```diff
-dnscontrol -dev
+DNSControl dev
```

### DNSControl TypeScript

```shell
./dist/build_darwin_all/dnscontrol write-types
```
```text
Successfully wrote types-dnscontrol.d.ts
```

```shell
head types-dnscontrol.d.ts
```

```diff
// This file was automatically generated by DNSControl. Do not edit it directly.
// To update it, run `dnscontrol write-types`.

-// DNSControl version: "4.7.4-next" ("1bbf9c4293f6cd5127bf190ead5ed738dd11c437") built 19 Dec 23 12:28 CET
+// DNSControl 4.7.4-next
// WARNING: These type definitions are experimental and subject to change in future releases.

interface Domain {
    name: string;
    subdomain: string;
    registrar: unknown;
```

### Homebrew

For completeness the reporting of the current [Homebrew ldflags configuration](https://github.com/Homebrew/homebrew-core/blob/18dcb1f2eb62051f4e117dd6bb2cde2ed8c6744d/Formula/d/dnscontrol.rb)

```ruby
go_ldflags = %W[
  -s -w
  -X main.SHA=#{tap.user}
  -X main.Version=#{version}
  -X main.BuildTime=#{time.iso8601}
]
system "go", "build", *std_go_args(ldflags: go_ldflags)
```

```shell
./dnscontrol version
```
```text
dnscontrol 4.7.3 (Homebrew)
```

_P.S. This pull request is best reviewed by a commit-by-commit review._

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Looks good!

Could you remove the whitespace changes? (I guess we need to standardize on a YAML prettier :) ).

**Comment by cafferata** [comment]
> Could you remove the whitespace changes?

Done! 

_P.S. The reason why this was committed was because my IDE (GoLand) continuously implemented this format._

> (I guess we need to standardize on a YAML prettier :) ).

Yes certainly, already discussed and local branch with Prettier is almost ready.

**Comment by tlimoncelli** [comment]
If we make this change, we're going to have to do a pre-release and let people check it out.  We get a lot of complaints when that version string changes or breaks.

**Comment by cafferata** [comment]
That's a great idea! Would you like to arrange this? I am not able to do that myself. 😊

**Comment by tlimoncelli** [comment]
Sadly I had to revert this because the build broke https://github.com/StackExchange/dnscontrol/actions/runs/7390125976/job/20104387012

**Comment by cafferata** [comment]
> Sadly I had to revert this because the build broke

That's annoying, I could have seen this by running the GitHub Actions on my GitHub fork repository. Sorry! 😕

I have tried to reproduce this error locally. However, this has not been achieved. The GoReleaser output diff with [actions/runs/7390125976/job/20104387012](https://github.com/StackExchange/dnscontrol/actions/runs/7390125976/job/20104387012):

```diff
 • starting build...
 • loading                                          path=.goreleaser.yml
 • skipping validate...
 • loading environment variables
 • getting and validating git state
-  • git state                                      commit=7fc1d32fbbad5f8eb671397f96533e5e7fb0a0fc branch=cicd/goreleaser-version current_tag=v4.7.3 previous_tag=v4.7.2 dirty=true
+  • accepting to run without a git repository because this is a snapshot
+  • git state                                      commit=none branch=none current_tag=v0.0.0 previous_tag=<unknown> dirty=false
   • pipe skipped                                   reason=disabled during snapshot mode
 • parsing tag
 • setting defaults
 • snapshotting
-  • building snapshot...                           version=4.7.4-next
+  • building snapshot...                           version=0.0.1-next
 • running before hooks
   • running                                        hook=go fmt ./...
   • running                                        hook=go mod tidy
   • running                                        hook=go generate ./...
   • took: 8s
 • checking distribution directory
-  • cleaning dist
 • loading go mod information
 • build prerequisites
 • writing effective config file
   • writing                                        config=dist/config.yaml
 • building binaries
```

So I've try without the git directory. This GoReleaser build was also successful.

```shell
mv .git/ .git-move-directory-for-goreleaser-build/
```

The suggestion from the GitHub action leads me to the `go help build`

```text
  ⨯ build failed after 4s                    error=failed to build for windows_amd64_v1: exit status 1: error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
```

```text
The build flags are shared by the build, clean, get, install, list, run,
and test commands:

	-buildvcs
		Whether to stamp binaries with version control information
		("true", "false", or "auto"). By default ("auto"), version control
		information is stamped into a binary if the main package, the main module
		containing it, and the current directory are all in the same repository.
		Use -buildvcs=false to always omit version control information, or
		-buildvcs=true to error out if version control information is available but
		cannot be included due to a missing tool or ambiguous directory structure.
```

<details>
    <summary>Sources consulted</summary>

_Captured for archival purposes._

```text
https://github.com/golang/go/issues/49004
https://github.com/golang/go/issues/51748
https://github.com/golang/go/issues/53640
https://github.com/golang/go/issues/54852
https://github.com/pre-commit/pre-commit/issues/2722
```
</details>

Based on that, I started looking further at the current GitHub Actions. I tweaked this and now there is a working set-up. See GitHub pull request https://github.com/StackExchange/dnscontrol/pull/2761 containing a working build: https://github.com/cafferata/dnscontrol/actions/runs/7402715334/job/20141152040?pr=1

The additional commits compared to the previous GitHub pull request:

1. https://github.com/StackExchange/dnscontrol/commit/ab78f8ccac95110b66b188733b26eec8e60b3c5d CICD: GitHub Action: `actions/checkout@v4` added `fetch-depth: 0`.
2. https://github.com/StackExchange/dnscontrol/commit/63a41d258e3e786b73c995b0ba88759f25a040b9 CICD: GitHub Action: `goreleaser/goreleaser-action@v5` removed the default `distribution` value. 
3. https://github.com/StackExchange/dnscontrol/commit/e0efbc701ad40ac3019b7d12ad54f95609864f68 CICD: GitHub Action: `goreleaser/goreleaser-action@v5` removed the default `version` value. 
4. https://github.com/StackExchange/dnscontrol/commit/4c976f0c6d0702823190778576bbe196473f331a CICD: GitHub Action: `actions/setup-go@v4` added Go set-up.

Explanation of the additional commits:

**GoReleaser**

> **Fetch depthness**
> 
> Notice the `fetch-depth: 0` option on the `Checkout` workflow step. It is required for GoReleaser to work properly. Without that, GoReleaser might fail or behave incorrectly.

_https://goreleaser.com/ci/actions/#fetch-depthness_

**GitHub Action**

> **Fetch all history for all tags and branches**
> ```yaml
> - uses: actions/checkout@v4
>   with:
>     fetch-depth: 0
> ```

_https://github.com/actions/checkout?tab=readme-ov-file#fetch-all-history-for-all-tags-and-branches_

**Pull request merged**
