### PR TITLE
Run unit tests as part of build checks

### PR DESCRIPTION
**Pull request by MaxHorstmann**
Follow-up to https://github.com/StackExchange/dnscontrol/pull/922

Just the unit tests. Separate PR for integration tests.

Output from test run:

```
> Run go test ./...
go: downloading github.com/hexonet/go-sdk v3.5.0+incompatible
go: downloading github.com/babolivier/go-doh-client v0.0.0-20200723140836-2f86c709ac4a
go: downloading github.com/mittwald/go-powerdns v0.5.2
go: downloading github.com/digitalocean/godo v1.46.0
go: downloading github.com/dnsimple/dnsimple-go v0.62.0
go: downloading github.com/billputer/go-namecheap v0.0.0-20170915210158-0c7adb0710f8
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading golang.org/x/oauth2 v0.0.0-20200902213428-5d25da1a8d43
go: downloading github.com/go-acme/lego v2.7.2+incompatible
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/hashicorp/go-retryablehttp v0.6.7
go: downloading github.com/aws/aws-sdk-go v1.35.9
go: downloading github.com/miekg/dns v1.1.34
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/robertkrimen/otto v0.0.0-20200922221731-ef014fd054ac
go: downloading github.com/stretchr/testify v1.6.1
go: downloading gopkg.in/sourcemap.v1 v1.0.5
go: downloading golang.org/x/net v0.0.0-20201016165138-7b1cca2348c0
go: downloading gopkg.in/ns1/ns1-go.v2 v2.0.0-20170502175150-c563826f4cbe
go: downloading github.com/softlayer/softlayer-go v0.0.0-20170804160555-5e1c8cccc730
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/go-gandi/go-gandi v0.0.0-20200921091836-0d8a64b9cc09
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/nrdcg/goinwx v0.8.1
go: downloading github.com/pquerna/otp v1.2.0
go: downloading github.com/Azure/go-autorest v14.2.0+incompatible
go: downloading github.com/Azure/go-autorest/autorest v0.11.10
go: downloading github.com/Azure/go-autorest/autorest/to v0.4.0
go: downloading cloud.google.com/go v0.69.1
go: downloading golang.org/x/crypto v0.0.0-20201016220609-9e8e0b390897
go: downloading github.com/kolo/xmlrpc v0.0.0-20200310150728-e0350524596b
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/urfave/cli/v2 v2.2.0
go: downloading github.com/cenkalti/backoff v2.1.1+incompatible
go: downloading github.com/andreyvit/diff v0.0.0-20170406064948-c7f18ee00883
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/vultr/govultr v1.0.0
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading golang.org/x/sys v0.0.0-20201018121011-98379d014ca7
go: downloading github.com/gobwas/glob v0.2.4-0.20181002190808-e7a84e9525fe
go: downloading github.com/google/go-querystring v1.0.1-0.20190318165438-c8c88dbee036
go: downloading github.com/TomOnTime/utfutil v0.0.0-20200626160131-0b0178852c8f
go: downloading github.com/PuerkitoBio/goquery v1.6.0
go: downloading github.com/Azure/go-autorest/autorest/azure/auth v0.5.3
go: downloading github.com/DisposaBoy/JsonConfigReader v0.0.0-20171218180944-5ea4d0ddac55
go: downloading github.com/exoscale/egoscale v0.23.0
go: downloading github.com/philhug/opensrs-go v0.0.0-20171126225031-9dfa7433020d
go: downloading github.com/Azure/go-autorest/autorest/azure/cli v0.4.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/gofrs/uuid v3.2.0+incompatible
go: downloading google.golang.org/api v0.33.0
go: downloading github.com/Azure/go-autorest/autorest/adal v0.9.5
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/andybalholm/cascadia v1.2.0
go: downloading github.com/boombuler/barcode v1.0.1-0.20190219062509-6c824513bacc
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/mitchellh/mapstructure v1.3.3
go: downloading github.com/renier/xmlrpc v0.0.0-20170708154548-ce4a1a486c03
go: downloading github.com/form3tech-oss/jwt-go v3.2.2+incompatible
go: downloading github.com/Azure/go-autorest/autorest/date v0.3.0
go: downloading github.com/Azure/go-autorest/tracing v0.6.0
go: downloading github.com/tdewolff/minify v2.3.6+incompatible
go: downloading github.com/Azure/go-autorest/logger v0.2.0
go: downloading github.com/mjibson/esc v0.2.0
go: downloading github.com/Azure/azure-sdk-for-go v47.0.0+incompatible
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/namedotcom/go v0.0.0-20180403034216-08470befbe04
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/tdewolff/parse v2.3.4+incompatible
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading golang.org/x/tools v0.0.0-20201017001424-6003fad69a88
go: downloading github.com/dimchansky/utfbom v1.1.0
go: downloading github.com/pierrec/lz4 v2.0.5+incompatible
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/jmespath/go-jmespath v0.4.0
go: downloading github.com/ovh/go-ovh v0.0.0-20181109152953-ba5adb4cf014
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading gopkg.in/yaml.v3 v3.0.0-20200605160147-a5ece683394c
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading gopkg.in/ini.v1 v1.42.0
go: downloading golang.org/x/mod v0.3.0
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading google.golang.org/grpc v1.32.0
go: downloading go.opencensus.io v0.22.5
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading github.com/golang/protobuf v1.4.3
go: downloading google.golang.org/genproto v0.0.0-20201015140912-32ed001d685c
go: downloading google.golang.org/protobuf v1.25.0
?   	github.com/StackExchange/dnscontrol/v3	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/build	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/build/generate	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/build/validate	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/cmd/convertzone	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/commands	0.033s
ok  	github.com/StackExchange/dnscontrol/v3/integrationTest	0.009s
ok  	github.com/StackExchange/dnscontrol/v3/models	0.005s
?   	github.com/StackExchange/dnscontrol/v3/pkg/acme	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/pkg/diff	0.023s
ok  	github.com/StackExchange/dnscontrol/v3/pkg/js	0.574s
?   	github.com/StackExchange/dnscontrol/v3/pkg/nameservers	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/pkg/natsort	0.003s
ok  	github.com/StackExchange/dnscontrol/v3/pkg/normalize	0.006s
?   	github.com/StackExchange/dnscontrol/v3/pkg/notifications	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/pkg/prettyzone	0.013s
ok  	github.com/StackExchange/dnscontrol/v3/pkg/printer	0.006s
ok  	github.com/StackExchange/dnscontrol/v3/pkg/spflib	0.343s
ok  	github.com/StackExchange/dnscontrol/v3/pkg/transform	0.005s
?   	github.com/StackExchange/dnscontrol/v3/pkg/version	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/providers/activedir	0.004s
?   	github.com/StackExchange/dnscontrol/v3/providers/axfrddns	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/azuredns	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/providers/bind	0.005s
ok  	github.com/StackExchange/dnscontrol/v3/providers/cloudflare	0.006s
?   	github.com/StackExchange/dnscontrol/v3/providers/cloudns	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/config	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/cscglobal	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/desec	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/digitalocean	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/dnsimple	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/doh	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/exoscale	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/providers/gandi_v5	0.018s
?   	github.com/StackExchange/dnscontrol/v3/providers/gcloud	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/hedns	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/hetzner	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/providers/hexonet	0.005s
?   	github.com/StackExchange/dnscontrol/v3/providers/internetbs	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/inwx	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/providers/linode	0.005s
?   	github.com/StackExchange/dnscontrol/v3/providers/namecheap	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/providers/namedotcom	0.008s
?   	github.com/StackExchange/dnscontrol/v3/providers/netcup	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/ns1	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/octodns	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/providers/octodns/octoyaml	0.088s
?   	github.com/StackExchange/dnscontrol/v3/providers/opensrs	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/ovh	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/powerdns	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/providers/route53	0.006s
?   	github.com/StackExchange/dnscontrol/v3/providers/softlayer	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/providers/vultr	0.006s
```

### CODE REVIEW

**Comment by MaxHorstmann** [comment]
@tlimoncelli quick review? If my understanding is correct, `go test ./...` runs unit tests whereas  `go test -provider $PROVIDER` runs integration tests for the provider.

**Review by tlimoncelli — APPROVED** [review]
LGTM

**Comment by tlimoncelli** [comment]
P.S. Yes, "go test" is unit tests and the other is integration tests.

**Comment by MaxHorstmann** [comment]
ok cool. I'll merge this in already, since it immediately adds value.

**Pull request merged**
