### PR TITLE
VULTR: fix failing integration tests

### PR DESCRIPTION
**Pull request by androw**
see #1902
IDN CNAME Target still hangs

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Thanks!

**Comment by tlimoncelli** [comment]
CircleCI is reporting an error:

```
Failed
=== RUN   TestConversion
    convert_test.go:71: Vultr record conversion mismatch { SRV _ssh_.tcp 5 22 ssh.example.com 5 300} 5 5 22 ssh.example.com. &{0 SRV _ssh_.tcp 5 22 ssh.example.com. 5 300}
--- FAIL: TestConversion (0.00s)
```

**Comment by androw** [comment]
Fixed!

But CAA is failing:

```
=== RUN   TestDNSProviders/androw.cf/14:CAA:CAA_whitespace
    integration_test.go:223: MODIFY CAA androw.cf: (128 issuewild ";" ttl=300) -> (0 issue "letsencrypt.org; validationmethods=dns-01; accounturi=https://acme-v02.api.letsencrypt.org/acme/acct/1234" ttl=300); Vultr RecordID: 2bf0fd02-4e98-42dd-b6ba-5e8e83b5e395
    integration_test.go:227: {"error":"Unable to update record: Data must be in the format: [flag] [iodef|issuewild|issue] \"domain\"","status":400}
```

Looks like Vultr supports domain only

**Comment by tlimoncelli** [comment]
Looks like VULTR doesn't support CAA targets with whitespace.  You can skip this test by updating `auditrecords.go` with:

```
  a.Add("CAA", rejectif.CaaTargetContainsWhitespace) // Last verified 2023-01-19
```

If you want to get fancy, you could write a new rejectif method that verifies the record matches `[flag] [iodef|issuewild|issue] \"domain\""`

Tom

**Comment by androw** [comment]
Fixed

**Comment by tlimoncelli** [comment]
Thanks!

**Pull request merged**
