### PR TITLE
RWTH: Adopt diff2 in compatibility mode

### PR DESCRIPTION
**Pull request by tlimoncelli**
Hi @mistererwin:

In reference to replacing pkg/diff with the new pkg/diff2 (https://github.com/StackExchange/dnscontrol/issues/1854)

I've introduced a compatibility mode to pkg/diff2 to make it easier for providers to adopt the new system.  If you do a diff with "hide whitespace", you'll see the changes are minimal.

I've taken the liberty of providing this PR as a starting point.

Please run the integration tests and let me know the result. (If you're getting this, I probably don't have access to an account on this provider)

Please run:
```
    cd integrationTest 
    go test -v -verbose -provider RWTH
```
and
```
    cd integrationTest
    go test -v -verbose -provider RWTH -diff2
```

They should both complete with no failures. Please fix any failures or loop me in for help.

If you are interested in porting to the new pkg/diff2/By*() functions, I'd be glad to accept a PR. However using the compatibility mode is sufficient if all tests pass.

Thanks and happy new years!!!

Tom
@tlimoncelli

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Friendly ping? @mistererwin

**Comment by tlimoncelli** [comment]
Friendly ping? @MisterErwin

**Comment by tlimoncelli** [comment]
Friendly ping?  @mistererwin

**Comment by MisterErwin** [comment]
Apologies for being non-responsive and thank your for the diff2-ing.

Due to the nature of domains managed by the RWTH NOC, the integration tests fail due to the lack of an empty test zone  (although it motivated me enough to try to convince the NOC to provide me with access to a test environment).

But from testing this branches' changes for some time in our prod environment (:sweat_smile:)  I can report it working fine so far.

I'll also get back to you once I manage to get an integration test zone to run.

**Comment by tlimoncelli** [comment]
Thanks for the update!  I'll merge. It should be fine.

**Pull request merged**
