### PR TITLE
CNR Provider: Review CI / Docs / Capabilities (add NAPTR, SSHFP)

### PR DESCRIPTION
**Pull request by tlimoncelli**
@tlimoncelli I went through all the capabilities and played around with the CentralNic Reseller API. All this is now updated and great that I've been able to identify SSHFP and NAPTR as supported record types.
Finally, I went through the Dev Guide for new Provider Modules and reviewed the missing parts. 

* Reviewed Provider Capabilities
* Added support for NAPTR record
* Added support for SSHFP record
* reviewed documentation
  * cleanup requested providers
  * added CNR to the provider list
* reviewed reported linting issues (golangci-lint)
* fixed go releaser regexp

Integration Tests passed:

```
...
--- PASS: TestDualProviders (4.89s)
=== RUN   TestNameserverDots
No nameservers found
=== RUN   TestNameserverDots/No_trailing_dot_in_nameserver
--- PASS: TestNameserverDots (0.12s)
    --- PASS: TestNameserverDots/No_trailing_dot_in_nameserver (0.00s)
PASS
ok      github.com/StackExchange/dnscontrol/v4/integrationTest  381.239s
```

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Hey @KaiSchwarz-cnic @AsifNawaz-cnic !

I want to include this in the new release that's going out tonight.  I made 1 change (fixed the merge conflict) but otherwise it's the same as https://github.com/StackExchange/dnscontrol/pull/3235.  Sadly I don't know how to manipulate github so that it git history shows this as your contribution to the repo, but I'll manually edit the release notes.

Thanks for the enhancements!  Looks like your registrar is starting a new chapter!  I'm glad you're bringing DNSControl along with you!

Tom

**Comment by AsifNawaz-cnic** [comment]
Thank you, @tlimoncelli, for your continuous support and efforts in bringing DNSControl for CNR into action.

**Comment by KaiSchwarz-cnic** [comment]
@tlimoncelli

I have no concerns regarding the commit history. Just important that our collaboration proceeds smoothly and that parties involved are satisfied. :-)

Wishing you a wonderful end of the year.

**Comment by tlimoncelli** [comment]
> I have no concerns regarding the commit history. Just important that our collaboration proceeds smoothly and that parties involved are satisfied. :-)

Thank you for being so flexible!

**Pull request merged**
