### PR TITLE
DOCS: Add NAPTR doc

### PR DESCRIPTION
**Pull request by systemcrash**

### CODE REVIEW

**Comment by cafferata** [comment]
Would you like to add this new `NAPTR` documentation entry to `SUMMARY.md`?

```diff
    * [NAMESERVER](functions/domain/NAMESERVER.md)
    * [NAMESERVER_TTL](functions/domain/NAMESERVER_TTL.md)
+   * [NAPTR](functions/domain/NAPTR.md)
    * [NO_PURGE](functions/domain/NO_PURGE.md)
    * [NS](functions/domain/NS.md)
```

**Comment by systemcrash** [comment]
Sure. Good point. Fixed.

**Comment by tlimoncelli** [comment]
Wow!  You really included a ton of info about NAPTR.  Do you use NAPTR records a lot?

**Comment by systemcrash** [comment]
Well, I've got a wealth of SIP experience, so working with NAPTR happens occasionally 😄

**Pull request merged**
