### PR TITLE
TRANSIP: Implementation get-zones all

### PR DESCRIPTION
**Pull request by cafferata**
```shell
~/dnscontrol/ dnscontrol get-zones transip - all
```
```text
$ORIGIN cafferata.dev.
$TTL 86400
@                IN MX    10 ASPMX.l.google.com.
                 IN MX    20 alt1.ASPMX.l.google.com.
                 IN MX    30 alt2.ASPMX.l.google.com.
                 IN MX    40 ASPMX2.googlemail.com.
                 IN MX    50 ASPMX3.googlemail.com.
                 IN MX    60 ASPMX4.googlemail.com.
                 IN MX    70 ASPMX5.googlemail.com.
                 IN TXT   "v=spf1 -all"
```

cc: @blackshadev

### CODE REVIEW

**Comment by blackshadev** [comment]
lgtm, nice work! I didn't know about this GetZones interface.

I see the branch is out of date, could you rebase on `master`?

**Comment by blackshadev** [comment]
I think @tlimoncelli wants you to rebase instead of creating a merge commit. But I will leave that up to @tlimoncelli to decide since he is the maintainer.

**Comment by cafferata** [comment]
Thought I'd give the 'update branch' feature within GitHub a try. 🤷‍♂️ I also prefer a 'rebase', fixed anyway. 👌

**Comment by tlimoncelli** [comment]
I'm in the rebase camp but I'm not offended by the use of merge :-) .  (Personally I have a git alias `p = pull --rebase --ff-only --prune`)

(and, yes, by completing the ZoneLister interface, the feature magically appears. Go is pretty cool)

Tom

**Pull request merged**
