### PR TITLE
CLOUDFLARE: sometime ago they bump down the min ttl to 60 second

### PR DESCRIPTION
**Pull request by andrewvmail**
#1952

### CODE REVIEW

**Comment by cafferata** [comment]
Cool! Can you also update the docs wrote by @tlimoncelli in https://github.com/StackExchange/dnscontrol/pull/1986?

**Comment by andrewvmail** [comment]
Ok, updated the docs

**Comment by cafferata** [comment]
Thanks @andrewvmail! 👍

**Comment by tlimoncelli** [comment]
Thanks for the update!

**Pull request merged**
