### PR TITLE
TRANSIP: Update go module to v6.19.0

### PR DESCRIPTION
**Pull request by cafferata**
No relevant TransIP API endpoints or DNSControl implementations have been changed. See the GitHub change log [transip/gotransip v6.19.0](https://github.com/transip/gotransip/releases/tag/v6.19.0). cc: @blackshadev

### CODE REVIEW

**Comment by cafferata** [comment]
@tlimoncelli @blackshadev are these Go TransIP module update pull requests appreciated? I see the TransIP updates coming from the internal tooling and simply port them back to DNSControl.

**Comment by blackshadev** [comment]
I appreciate te effort. Eventhough our api 's aren't effected, keeping your dependencies up to date is always a welcome addition.
I don't see the updates... Or I see to many and thus ignore them...
Anyway, thx!

**Comment by cafferata** [comment]
It's always the question, how would DNSControl/you like being up-to-date? Is this by patching& updating every version? Or is this scheduled/time based or something like that? But it's good to know that you can appreciate it. 👍

**Comment by tlimoncelli** [comment]
I don't have a strict answer.  I'm happy if dependencies are updated quarterly.  If an API breaks, it should be updated sooner.  Security-related updates should be done asap (10 days is the goal)

**Pull request merged**
