### PR TITLE
OPENSRS: Update README and other documentation

### PR DESCRIPTION
**Pull request by tlimoncelli**

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Hi @philhug!

Some how the OpenSRS provider that you contributed was missing changes to the README.md and other files.  I've filled in some placeholders in this PR, but I'd appreciate it if you could take over and finish this.

**Comment by tlimoncelli** [comment]
oops... I put a comment in the wrong PR.

**Comment by philhug** [comment]
Anything to do?

**Comment by tlimoncelli** [comment]
I've started a feature branch. See https://github.com/StackExchange/dnscontrol/issues/458

**Pull request closed without merging**
