### PR TITLE
BUILD SYSTEM: Skip unused integration tests faster

### LINKED ISSUE #1934: BUILD SYSTEM: skip unused integration tests faster
It takes 25 seconds to skip an integration test that isn't activated (the `provider_DOMAIN` env variable isn't set).  This is because it spins up a container just to run the bash `if` statement. That seems pretty wasteful.

I bet we could use the new conditional steps feature [(See this article)](https://support.circleci.com/hc/en-us/articles/360043638052-Conditional-steps-in-jobs-and-conditional-workflows) to have the "job" exit early if `$<< parameters.provider >>_DOMAIN` is not set.

CC: @cdhunt

### PR DESCRIPTION
**Pull request by cdhunt**
fixes #1934

### CODE REVIEW

**Comment by cafferata** [comment]
Don't forget to change the documentation ;-)

- https://github.com/StackExchange/dnscontrol/blob/46d5666/docs/release-engineering.md?plain=1#L225
- https://stackexchange.github.io/dnscontrol/release-engineering#:~:text=Tests%20that%20are%20skipped%20take%2025%2D30%20seconds%20to%20complete

**Comment by tlimoncelli** [comment]
Great!  This sped things up from 25 seconds to 3 seconds.  Huge improvement!  Thanks!

**Comment by cafferata** [comment]
@tlimoncelli @cdhunt have you perhaps overlooked [my comment](https://github.com/StackExchange/dnscontrol/pull/1939#issuecomment-1382697279) about the documentation change?

**Comment by tlimoncelli** [comment]
> @tlimoncelli @cdhunt have you perhaps overlooked [my comment](https://github.com/StackExchange/dnscontrol/pull/1939#issuecomment-1382697279) about the documentation change?

That'll be done in https://github.com/StackExchange/dnscontrol/pull/1951

**Pull request merged**
