### PR TITLE
PACKETFRAME: Adopt diff2 in compatibility mode

### PR DESCRIPTION
**Pull request by tlimoncelli**
Hi @hamptonmoore:

In reference to replacing pkg/diff with the new pkg/diff2 (https://github.com/StackExchange/dnscontrol/issues/1854)

I've introduced a compatibility mode to pkg/diff2 to make it easier for providers to adopt the new system.  If you do a diff with "hide whitespace", you'll see the changes are minimal.

I've taken the liberty of providing this PR as a starting point.

Please run the integration tests and let me know the result. (If you're getting this, I probably don't have access to an account on this provider)

Please run:
```
    go test -v -verbose -provider PACKETFRAME
```
and
```
    go test -v -verbose -provider PACKETFRAME -diff2
```

They should both complete with no failures. Please fix any failures or loop me in for help.

If you are interested in porting to the new pkg/diff2/By*() functions, I'd be glad to accept a PR. However using the compatibility mode is sufficient if all tests pass.

Thanks and happy new years!!!

Tom
@tlimoncelli

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Friendly ping? @hamptonmoore

**Comment by tlimoncelli** [comment]
Friendly ping?  @hamptonmoore  
I just need you to run the test with and with `-diff2` to see if the results are the same.

**Comment by hamptonmoore** [comment]
Apologies! Been getting lots of github notifications from work and this one kept getting swept under the rug, will do today

**Comment by hamptonmoore** [comment]
@tlimoncelli Apologies, what directory am I meant to be running it from. Both the root directory and /providers/packetframe return with
```
➜  dnscontrol git:(tlim_diff2_packetframe)     go test -v -verbose -provider PACKETFRAME -diff2

?       github.com/StackExchange/dnscontrol/v3  [no test files]
```

**Comment by cafferata** [comment]
I have seen this question in another diff2 pull request.  @tlimoncelli his answer was three missing 'integrationTest' directory. 

```shell
cd integrationTest
```

Current diff:

```shell 
go test -v -verbose -provider PACKETFRAME
```

and `diff2`:

```shell
go test -v -verbose -provider PACKETFRAME -diff2
```

**Comment by tlimoncelli** [comment]
I'm going to take the liberty of merging this.  The change turns out to be very low risk plus if there are problems, they will be discovered in the next phase of the diff2 plan.

**Pull request merged**
