### PR TITLE
extend D_EXTEND to handle subdomains

### PR DESCRIPTION
**Pull request by ad8-bdl**
Ref. #858

### CODE REVIEW

**Comment by tlimoncelli** [comment]
I added some parse_tests to verify things work as expected on the edge cases I mentioned before.  You can merge in my changes from https://github.com/StackExchange/dnscontrol/pull/872

Currently those tests fail. Please check my work... it's certainly possible my test data is invalid.

That said, I think the problem is with `_getDomainObject()`.  I think the algorithm should be along the lines of

* Split foo.bar.com into ["foo", "bar", "com"]
* Search for "foo.bar.com"
* Search for "bar.com"
* Search for "com"
* Return null

**Comment by ad8-bdl** [comment]
Will do - how do I run these tests?

________________________________

**Comment by tlimoncelli** [comment]
> Will do - how do I run these tests?

    go test -count=1 pkg/js/*.go

or

    cd pkg/js && go test -count=1

**Comment by ad8-bdl** [comment]
On `_getDomainObject`: oops, yes the previous approach returned on the first match, not necessarily the best match. Fixed.

`_getDomainObject` still uses a 'truncated string comparison' approach rather than explicitly breaking down the paths to arrays and doing a piece-wise comparison of those paths, as the string comparison is much simpler than effectively the same process on arrays.

**Comment by mikenz** [comment]
I love this proposed change! It's going to make my config so much easier to follow.

**Comment by ad8-bdl** [comment]
Sooo, re. CNAMEs and its siblings: making the target fully qualified in `helpers.js` (as 929cd4711d323c5ce24a0a42f301774cc93967fc does) is not a great approach, as it makes CNAMEs/etc behave differently depending on whether they are in a D() or D_EXTEND().

Instead it seems much better to propagate the information on the subdomain through to `validate:ValidateAndNormalizeConfig`, so that it can be properly assembled in the canonicalise step. Same for all of CNAME, MX, NAPTR, NS and SRV. (I tested all bar NAPTR on Cloudflare).

**Comment by ad8-bdl** [comment]
Ok, so with that - I believe it's good to go.

**Comment by tlimoncelli** [comment]
I've been busy with other stuff for a bit so I may be a little out of touch and/or confused.

I think https://github.com/StackExchange/dnscontrol/pull/872 needs to be merged into https://github.com/StackExchange/dnscontrol/pull/870 before it can be merged to master.

I'll be focusing on dnscontrol a lot the next few days.  Let me know how I can help!

**Comment by ad8-bdl** [comment]
I hope I've got that right...

**Comment by tlimoncelli** [comment]
We're so close!  Sadly I found a bug:

```
D("domain.tld", REG, DnsProvider(DNS),
  A("@", "127.0.0.1"),
  A("a", "127.0.0.2"),
  CNAME("b", "c")
);

D("sub.domain.tld", REG, DnsProvider(DNS),
  A("@", "127.0.1.1"),
  A("aa", "127.0.1.2"),
  CNAME("bb", "cc")
);


// Should extend domain.tld, but currently extends sub.domain.tld 
D_EXTEND("ssub.domain.tld",
  A("@", "127.0.0.7"),
  A("j", "127.0.0.8"),
  CNAME("k", "l")
);

```

**Comment by tlimoncelli** [comment]
Here's a PR with the failing test: https://github.com/StackExchange/dnscontrol/pull/885

**Comment by tlimoncelli** [comment]
Merged as part of https://github.com/StackExchange/dnscontrol/commit/b275286dae653b0c3193515897b087d227c3c66b

**Pull request closed without merging**
