### PR TITLE
ROUTE53: Allow R53_ALIAS records to enable target health evaluation

### PR DESCRIPTION
**Pull request by jonathanbouvier**
R53_ALIAS records have a property which allows them to evaluate target health. This was previously hardcoded to false for all R53_ALIAS records.

This has been added as a new record modifier instead of a new parameter to R53_ALIAS to remain backwards compatible. The previous default behavior has been maintained.

- Add R53_EVALUATE_TARGET_HEALTH record modifier to enable this behavior
- Update provider to account for this setting during record conversion
- Update RecordConfig receivers to allow this setting to be detected during diff
- Update getZones command to include this setting in dumped config
- Update tests
- Update documentation

### CODE REVIEW

**Comment by tlimoncelli** [comment]
CC @vatsalyagoel for visibility.

Wow!  Jonathan, I gotta say this is an impressive PR!   Adding record meta modifiers is not well documented but it looks like you got it all right!  Plus you've included documentation and tests!  Thanks!

I'll merge this before the next release unless @vatsalyagoel has any comments/corrections.

**Comment by jonathanbouvier** [comment]
Thanks @tlimoncelli ! Happy to help.

I'm looking to use dnscontrol to manage some of my more complicated Route53 zones, but I think I'm going to need some additional features in the Route53 provider. Alias target health evaluation was just one of the first challenges I encountered.

Eventually, I'd love to add support for some (or all) of the various routing policies supported by Route53:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html

**Comment by tlimoncelli** [comment]
Oops!  I meant to CC  @tresni instead of @vatsalyagoel.  (Copy-and-paste error!)

**Comment by tlimoncelli** [comment]
> Eventually, I'd love to add support for some (or all) of the various routing policies supported by Route53:

Sounds good to me!

Oh, I just noticed one thing I'd like to see added to this PR.  Could you add integration tests to `integrationTest/integration_test.go`?  You could probably just add to the existing tests. Search for `ROUTE53 features` to see them.

**Comment by jonathanbouvier** [comment]
> > Eventually, I'd love to add support for some (or all) of the various routing policies supported by Route53:
> 
> Sounds good to me!
> 
> Oh, I just noticed one thing I'd like to see added to this PR. Could you add integration tests to `integrationTest/integration_test.go`? You could probably just add to the existing tests. Search for `ROUTE53 features` to see them.

I just modified/added integration tests.

```
go test -provider ROUTE53
PASS
ok  	github.com/StackExchange/dnscontrol/v4/integrationTest	107.350s
```

**Review by tlimoncelli — APPROVED** [review]

**Comment by tlimoncelli** [comment]
Great!  Thanks!

**Pull request merged**
