### PR TITLE
DOCS: Merge toc and index

### PR DESCRIPTION
**Pull request by cafferata**
I regularly lose the structure of the website (I'm mostly reading from mobile view). This is partly because there is an incomplete TOC, and other content/features are linked from the homepage. That's why I suggest removing the TOC. This was only from 1 place (`Homepage` > `You can also view a list of all topics`) linked in. Now the menu always links to the five sections:

1. `Getting Started`
2. `Reference`
3. `Advanced features`
4. `Commands`
5. `Developer Info`

For the sake of completeness, I have made an overview of all content from the root directory /docs/ with the check whether this page is available from the homepage.

|Content|Linked from index?|Where then?|
|---|---|---|
|[adding-new-rtypes.md](https://stackexchange.github.io/dnscontrol/adding-new-rtypes)|✅||
|[alias.md](https://stackexchange.github.io/dnscontrol/alias)|✅||
|[bug-triage.md](https://stackexchange.github.io/dnscontrol/bug-triage)|✅||
|[byo-secrets.md](https://stackexchange.github.io/dnscontrol/byo-secrets)|✅||
|[caa-builder.md](https://stackexchange.github.io/dnscontrol/caa-builder)|✅||
|[check-creds.md](https://stackexchange.github.io/dnscontrol/check-creds)|✅||
|[ci-cd-gitlab.md](https://stackexchange.github.io/dnscontrol/ci-cd-gitlab)|✅||
|[cli-variables.md](https://stackexchange.github.io/dnscontrol/cli-variables)|✅||
|[code-tricks.md](https://stackexchange.github.io/dnscontrol/code-tricks)|✅||
|[creds-json.md](https://stackexchange.github.io/dnscontrol/creds-json)|✅||
|[documentation.md](https://stackexchange.github.io/dnscontrol/documentation)|✅||
|[examples.md](https://stackexchange.github.io/dnscontrol/examples)|✅||
|[get-certs.md](https://stackexchange.github.io/dnscontrol/get-certs)|✅||
|[get-zones.md](https://stackexchange.github.io/dnscontrol/get-zones)|✅||
|[getting-started.md](https://stackexchange.github.io/dnscontrol/getting-started)|✅||
|[index.md](https://stackexchange.github.io/dnscontrol/index)|✅||
|[js.md](https://stackexchange.github.io/dnscontrol/js)|✅||
|[migrating.md](https://stackexchange.github.io/dnscontrol/migrating)|✅||
|[nameservers.md](https://stackexchange.github.io/dnscontrol/nameservers)|✅||
|[notifications.md](https://stackexchange.github.io/dnscontrol/notifications)|✅||
|[opinions.md](https://stackexchange.github.io/dnscontrol/opinions)|✅||
|[provider-list.md](https://stackexchange.github.io/dnscontrol/provider-list)|✅||
|[release-engineering.md](https://stackexchange.github.io/dnscontrol/release-engineering)|✅||
|[spf-optimizer.md](https://stackexchange.github.io/dnscontrol/spf-optimizer)|✅||
|[testing-txt-records.md](https://stackexchange.github.io/dnscontrol/testing-txt-records)|❌|writing-providers|
|[unittests.md](https://stackexchange.github.io/dnscontrol/unittests)|✅||
|[v316.md](https://stackexchange.github.io/dnscontrol/v316)|❌|Nowhere?|
|[why-the-dot.md](https://stackexchange.github.io/dnscontrol/why-the-dot)|✅||
|[writing-providers.md](https://stackexchange.github.io/dnscontrol/writing-providers)|✅||

### CODE REVIEW

**Comment by tlimoncelli** [comment]
To be totally transparent, I've never looked at the website from a mobile browser until you mentioned it here.  Now I see what you mean about the TOC missing items.  However, I never thought of the top bar as being a TOC.  I think of it as guiding a new visitor to a few pages of interest.

Would it be possible to have it both ways?  that is, mobile showing the TOC but the non-mobile version having links directly to the getting start page, the language reference, and the list of providers?

**Comment by cafferata** [comment]
I'm not sure we fully understand each other. The current [TOC](https://stackexchange.github.io/dnscontrol/toc) contains fewer links than the [homepage](https://stackexchange.github.io/dnscontrol/). This has nothing to do with the mobile view. 

On the mobile view you will be disoriented faster. Because the header menu only shows three text links:
1. [Getting Started](https://stackexchange.github.io/dnscontrol/getting-started)
1. [Language Reference](https://stackexchange.github.io/dnscontrol/js)
1. [Providers](https://stackexchange.github.io/dnscontrol/provider-list)

These three items do not refer to the homepage, so the rest of the content disappears from view. That has been the main reason for using the section header names as menu items. Partly because there are no in-between pages to link to.

Maybe it's better to leave the changes in the menu out of this PR and leave it alone? Then all the TOC content and the index are merged into one.

**Comment by cafferata** [comment]
I've add an extra commit https://github.com/StackExchange/dnscontrol/pull/1789/commits/dc8ec82d578cf0de9dfae27292896f6e1d4dffe8 to switch the header menu items between mobile view and all other views. If you ask me, ready to merge. 👍

**Comment by tlimoncelli** [comment]
Yes!  That's so much better! Thanks!  (you have awesome HTML skills!)

**Pull request merged**
