### PR TITLE
CICD: Rename the master branch to main

### PR DESCRIPTION
**Pull request by cafferata**
Rename the "master" branch to be "main". Fixes https://github.com/StackExchange/dnscontrol/issues/2701.

⚠️ **WARNING**
1. This work cannot be merged without making the GitHub repository branch `main` available.
2. ~~In addition, this GitHub pull request conflicts with https://github.com/StackExchange/dnscontrol/pull/2767/files#diff-9844a181252db64e648f9c9e864423bc8b27727870fb9b4b4dc8dd52181ab00eR160~~

### CODE REVIEW

**Comment by tlimoncelli** [comment]
Would you recommend merging this right before or right after a release?

**Comment by cafferata** [comment]
This refactor work does not provide any added value before the release, so I would say 'once' after the release.

**Step-by-step plan**
1. Merge GitHub pull request https://github.com/StackExchange/dnscontrol/pull/2774.
2. Create the `main` branch, two options:
    1. **Local**
        1. Push de local up to date branch `master` to the remote branch `main`.
        ```shell
        git push origin master:main
        ```
    2. **GitHub interface**
        1. Go to [StackExchange/dnscontrol/branches](https://github.com/StackExchange/dnscontrol/branches).
        2. Click `New branch`.
        3. Fill in `New branch name`: `main`.
3. Change the `Default branch`.
    1. Now you need to change the default branch within the GitHub [StackExchange/dnscontrol/settings](https://github.com/StackExchange/dnscontrol/settings).
    2. Click the `Switch to another branch` under `Default branch`.
    3. Choose `main`.
    4. Click `Update`.

Done, another issue solved! 🚢

**Comment by cafferata** [comment]
Resolved the git merge conflicts with the upstream.

**Comment by tlimoncelli** [comment]
@cafferata It turns out that Github makes this a lot easier.  Just go to https://github.com/TomOnTime/ocd/settings and change the default branch to `main`.  It will rename the master branch to main for you.  Pretty cool!

**Pull request merged**
