### PR TITLE
Add "get-zone" command

### PR DESCRIPTION
**Pull request by tlimoncelli**
* Related to https://github.com/StackExchange/dnscontrol/issues/539
* Fixes https://github.com/StackExchange/dnscontrol/issues/538
* Fixes https://github.com/StackExchange/dnscontrol/issues/576
* Fixes https://github.com/StackExchange/dnscontrol/issues/609
* Fixes https://github.com/StackExchange/dnscontrol/issues/610

CC: @ad8-bdl

### CODE REVIEW

**Comment by tlimoncelli** [comment]
This is ready for testing.  Can people give it a try?

**Comment by captncraig** [comment]
I tried it! 

1. The help text `Arguments should be: zonename credskey providername (Ex: example.com r53 ROUTE53)` seems to have the parameter order reversed. Seems to be `credskey providername zonename`
2. That's as far as I got. Cloudflare is not implemented yet. I may implement and make a pr into this shortly.

A few general thoughts though from looking it over:

1. It would be really cool if we could enable converting **all** zones in your account in one go. For people who have dozens or more and don't want to run the tool multiple times and maybe miss one. That may require an additional "ListZones" or something on the interface though.
2. This is a really big change, so I get why doing it piecemeal is the easy path. I would like to see a end-product where all providers must implement the GetZoneRecord function, and do it consistently. I feel like the integration tests are a good vector to helping that, if we verify the result of GetZoneRecords after each changeset. I was also a little surprised Push/Preview don't use the new code, but maybe both of these are future steps. Maybe there is a mergeable middle ground before then.

**Comment by captncraig** [comment]
Awesome, I got it working with #625.

A few new notes:

1. Cloudflare uses metadata for the "orange cloud" proxy configuration. Right now the existing function to get records does not recreate that, but instead the driver queries the "original" record field to learn what it needs to know. It gets worse, because the "read-only" side of things doesn't really know whether to use "on" or "full" (I don't even remember which does what anymore). But maybe using "on" is an ok default for get-zone for records that are already enabled? `GetZoneRecords` could maybe add "on" to records it finds need it? Assuming `GetZoneRecords` creates the proper metadata, the dsl printer should probably output it. 

2. TTLs are always horrible. Cloudflare uses 1 as a default and my dsl output was littered with `TTL(1)`. I first changed the cloudflare code to replace 1 with 300, but then noticed the default is configurable. So I kinda went with the reverse of another convention we have used: "If `GetZoneRecords` gives you a 0 ttl, use the default value.". Is that sensible? Its in the PR above.

**Comment by tlimoncelli** [comment]
> I tried it!
> 
> 1. The help text `Arguments should be: zonename credskey providername (Ex: example.com r53 ROUTE53)` seems to have the parameter order reversed. Seems to be `credskey providername zonename`

Correct.  Will fix.

> 2. That's as far as I got. Cloudflare is not implemented yet. I may implement and make a pr into this shortly.

+1

> A few general thoughts though from looking it over:
> 
> 1. It would be really cool if we could enable converting **all** zones in your account in one go. For people who have dozens or more and don't want to run the tool multiple times and maybe miss one. That may require an additional "ListZones" or something on the interface though.

I saw your PR.  Looks good. I agree that a ZoneLister interface is the best way to go.

> 2. This is a really big change, so I get why doing it piecemeal is the easy path. I would like to see a end-product where all providers must implement the GetZoneRecord function, and do it consistently. I feel like the integration tests are a good vector to helping that, if we verify the result of GetZoneRecords after each changeset. I was also a little surprised Push/Preview don't use the new code, but maybe both of these are future steps. Maybe there is a mergeable middle ground before then.

I figured that it was easier to just add a function than require every provider to rewrite their GetDomainCorrections code.  I think that once people start complaining that "get-zone" doesn't work for a particular provider, the providers will step up.

**Comment by tlimoncelli** [comment]
> Awesome, I got it working with #625.
> 
> A few new notes:
> 
> 1. Cloudflare uses metadata for the "orange cloud" proxy configuration. Right now the existing function to get records does not recreate that, but instead the driver queries the "original" record field to learn what it needs to know. It gets worse, because the "read-only" side of things doesn't really know whether to use "on" or "full" (I don't even remember which does what anymore). But maybe using "on" is an ok default for get-zone for records that are already enabled? `GetZoneRecords` could maybe add "on" to records it finds need it? Assuming `GetZoneRecords` creates the proper metadata, the dsl printer should probably output it.

Interesting!  I hadn't thought about that.  I'll digest that more later.

> 2. TTLs are always horrible. Cloudflare uses 1 as a default and my dsl output was littered with `TTL(1)`. I first changed the cloudflare code to replace 1 with 300, but then noticed the default is configurable. So I kinda went with the reverse of another convention we have used: "If `GetZoneRecords` gives you a 0 ttl, use the default value.". Is that sensible? Its in the PR above.

Looks good.  I'll play with it a little and see what works best.

**Pull request merged**
