### PR TITLE
Add Exoscale provider

### PR DESCRIPTION
**Pull request by pierre-emmanuelJ**
Exoscale

# Exoscale European Cloud provider

Implement Exoscale provider to use DNS service

### CODE REVIEW

**Comment by captncraig** [comment]
Thanks for the contribution. Sorry I've been a bit slow to pick up on things (summer vacation). I will be reviewing this pr this week. Is there any kind of free testing / staging environment that can be used to test this out?

**Comment by greut** [comment]
Hey @llambiel, how can we accommodate this?

**Comment by greut** [comment]
@captncraig drop us an e-mail at support@exoscale.com and we may provide you with a coupon.

**Comment by captncraig** [comment]
This looks pretty goof to me. Can you confim the integration tests all run and pass?

**Comment by greut** [comment]
@captncraig ok, we still fail the DualProviders test case. /cc @pierre-emmanuelJ 
```
=== RUN   TestDualProviders
--- FAIL: TestDualProviders (5.02s)
    integration_test.go:179: Clearing everything
    integration_test.go:173: #1: DELETE TXT foo.test.exo "simple" ttl=300                                                                    
    integration_test.go:173: #2: DELETE A foo.test.exo 1.2.3.4 ttl=300
    integration_test.go:173: #3: DELETE A bar.test.exo 1.2.3.4 ttl=300
    integration_test.go:185: Adding nameservers from another provider
    integration_test.go:173: #1: CREATE NS test.exo ns1.otherdomain.tld. ttl=300                                                             
    integration_test.go:173: #2: CREATE NS test.exo ns2.otherdomain.tld. ttl=300                                                             
    integration_test.go:188: Running again to ensure stability
    integration_test.go:194: Expect no corrections on second run, but found 2.                                                               
    integration_test.go:196: #0: CREATE NS test.exo ns1.otherdomain.tld. ttl=300                                                             
    integration_test.go:196: #1: CREATE NS test.exo ns2.otherdomain.tld. ttl=300
```

**Comment by captncraig** [comment]
Is this still ready to merge. I'm willing to do that if it looks good to you.

**Comment by pierre-emmanuelJ** [comment]
Thanks I will check this today because DualProviders test fail

**Comment by pierre-emmanuelJ** [comment]
@captncraig I confim all integration tests run and pass! 😄

**Comment by tlimoncelli** [comment]
Thank you for contributing the new provider!

**Pull request merged**
