### PR TITLE
BUG: Errors while listing zones do not propagate through the system (#2474)

### PR DESCRIPTION
**Pull request by hmoffatt**
If an error occurred listing zones (eg invalid credentials), the preview/push commands didn't return an error code.

### CODE REVIEW

**Comment by hmoffatt** [comment]
Also discovered that CLOUDFLAREAPI caches an empty zone list if the fetch fails.

**Comment by tlimoncelli** [comment]
Good catch!

CC @tresni for approval.

**Comment by tlimoncelli** [comment]
Providers shouldn't generate any network traffic just at initialization time.  I guess I missed that when I reviewed ClouDNS.

We should probably add a `.CheckCreds()` method or something.  But so far nobody has complained not getting an error until the first domain of that provider.

**Comment by hmoffatt** [comment]
I've pushed another change for CLOUDNS to delay fetching the domain list.

**Comment by tlimoncelli** [comment]
Thanks for fixing this!!!

**Pull request merged**
