### PR TITLE
CHORE: Remove diff1 from codebase

### PR DESCRIPTION
**Pull request by tlimoncelli**
As announced in https://github.com/StackExchange/dnscontrol/issues/2262, it is time to remove the old diff code from the repo.

Since this is a large change, I'd like to hear back from the maintainers of any provider that uses the backwards compatibility layer (`diff1.NewCompat()` and friends) to confirm this doesn't break anything.

**Please mark your provider as complete by October 20, 2023.**  This will be merged Oct 21.

What to test:

1.  Run the integration tests (`cd integrationTest` then set env variables then `go test -v -verbose -provider PROVIDERNAME`)
2. Test is on your own DNS configuration (and others!)

The big change to the backwards compatibility layer is that notifications about `NO_PURGE` and `IGNORE()` now print when the related domain is processed.  Previously they were printed earlier, because the interface didn't support passing "inst.REPORT" messages. This has been fixed now that the old code has gone away. 

Feedback appreciated!  Questions encouraged! 

Tom

Provider list:

- [ ] akamaiedgedns @svernick
- [ ] cloudns @pragmaton
- [ ] cscglobal @mikenz
- [x] desec @D3luxee
- [x] digitalocean @Deraen
- [x] dnsimple @onlyhavecans
- [ ] dnsmadeeasy @vojtad
- [ ] domainnameshop @SimenBai
- [ ] exoscale @pierre-emmanuelJ
- [x] gcloud @riyadhalnur
- [x] hetzner @das7pad
- [x] hexonet @KaiSchwarz-cnic
- [x] hostingde @juliusrickert
- [ ] inwx @patschi
- [ ] linode @koesie10
- [x] loopia @systemcrash
- [x] namecheap @willpower232
- [ ] namedotcom NEEDS VOLUNTEER
- [ ] netcup @kordianbruck
- [ ] netlify @SphericalKat
- [x] oracle @kallsyms
- [ ] packetframe @hamptonmoore
- [ ] rwth @mistererwin
- [ ] softlayer NEEDS VOLUNTEER

### CODE REVIEW

**Comment by KaiSchwarz-cnic** [comment]
@tlimoncelli I run the integration tests for HEXONET with latest dnscontrol master. all Good.

**Comment by tlimoncelli** [comment]
@KaiSchwarz-cnic Thanks!

**Comment by riyadhalnur** [comment]
@tlimoncelli all good with gcloud

**Comment by patschi** [comment]
Running INWX provider through tests:

On the `master` branch:
```
[...]
--- PASS: TestNameserverDots (0.13s)
    --- PASS: TestNameserverDots/No_trailing_dot_in_nameserver (0.00s)
PASS
ok      github.com/StackExchange/dnscontrol/v4/integrationTest  73.968s
```

On branch `tlim_removediff1`:
```
[...]
--- PASS: TestNameserverDots (0.13s)
    --- PASS: TestNameserverDots/No_trailing_dot_in_nameserver (0.00s)
PASS
ok      github.com/StackExchange/dnscontrol/v4/integrationTest  77.696s
```

So LGTM from INWX provider perspective.

**Comment by willpower232** [comment]
Namecheap is no more broken than it usually is 🙏

**Comment by systemcrash** [comment]
* [✅]  loopia @systemcrash 

Ran against (b972cd608950ed98774c28cbee793b14f4e602f4):
```
git checkout tlim_removediff1
cd integrationTest
go test -v -verbose -provider LOOPIA
```

I'm satisfied with the results, that the changes are fairly safe, although some new UNEXPECTEDs with MX seem to have appeared recently:

```
=== RUN   TestDNSProviders/example.com/04:MX:Create_MX
    integration_test.go:247:
        + CREATE MX testmx.example.com 5 foo.com. ttl=300
    integration_test.go:268: Expected 0 corrections on second run, but found 1.
    integration_test.go:270: UNEXPECTED #0: ± MODIFY MX testmx.example.com: (5 foo.com.. ttl=300) -> (5 foo.com. ttl=300)

...
=== RUN   TestDNSProviders/example.com/07:manyTypesAtOnce:CreateManyTypesAtLabel
    integration_test.go:247:
        + CREATE MX testmx.example.com 100 bar.com. ttl=300
    integration_test.go:247:
        + CREATE MX testmx.example.com 5 foo.com. ttl=300
    integration_test.go:247:
        + CREATE A www.example.com 1.1.1.1 ttl=300
    integration_test.go:268: Expected 0 corrections on second run, but found 2.
    integration_test.go:270: UNEXPECTED #0: ± MODIFY MX testmx.example.com: (100 bar.com.. ttl=300) -> (100 bar.com. ttl=300)
    integration_test.go:270: UNEXPECTED #1: ± MODIFY MX testmx.example.com: (5 foo.com.. ttl=300) -> (5 foo.com. ttl=300)
...
=== RUN   TestDNSProviders/example.com/11:TypeChange:Change_to_MX
    integration_test.go:247:
        + CREATE MX foo.example.com 5 mx.google.com. ttl=300
    integration_test.go:247:
        - DELETE A foo.example.com 1.2.3.4 ttl=300
    integration_test.go:268: Expected 0 corrections on second run, but found 1.
    integration_test.go:270: UNEXPECTED #0: ± MODIFY MX foo.example.com: (5 mx.google.com.. ttl=300) -> (5 mx.google.com. ttl=300)
...
=== RUN   TestDNSProviders/example.com/14:MX:Record_pointing_to_@
    integration_test.go:247:
        + CREATE MX foo.example.com 8 example.com. ttl=300
    integration_test.go:268: Expected 0 corrections on second run, but found 1.
    integration_test.go:270: UNEXPECTED #0: ± MODIFY MX foo.example.com: (8 example.com.. ttl=300) -> (8 example.com. ttl=300)
...
=== RUN   TestDNSProviders/example.com/17:Case_Sensitivity:Create_CAPS
    integration_test.go:247:
        + CREATE MX bar.example.com 5 bar.com. ttl=300
    integration_test.go:268: Expected 0 corrections on second run, but found 1.
    integration_test.go:270: UNEXPECTED #0: ± MODIFY MX bar.example.com: (5 bar.com.. ttl=300) -> (5 bar.com. ttl=300)
...
```

Problems here, however:

```
=== RUN   TestDNSProviders/example.com/25:CAA:CAA_whitespace
    integration_test.go:247:
        ± MODIFY CAA example.com: (128 issuewild ";" ttl=300) -> (0 issue "letsencrypt.org; validationmethods=dns-01; accounturi=https://acme-v02.api.letsencrypt.org/acme/acct/1234" ttl=300)
    integration_test.go:252: RPC Error: (404) Unknown error
```

I'm seeking clarification from Loopia - as to what part of the valid CAA record they dislike. Seems like they're incapable of [RFC8657](https://www.rfc-editor.org/rfc/rfc8657). 

Might be an idea to split that test into a separate test case.

I don't remember this being a problem previously, so perhaps this is a new test case 😄 


```
=== RUN   TestDNSProviders/example.com/30:SRV:Null_Target
    integration_test.go:247:
        + CREATE SRV _sip._tcp.example.com 15 65 75 . ttl=300
    integration_test.go:252: RPC Error: (404) Unknown error
```

The SRV? Same split recommended. Seeking clarification from 💩  


I verified the above problem cases anew to ensure they weren't flukes with:
```
go test -v -verbose -provider LOOPIA -timeout 3600s -start 30 -end 30
go test -v -verbose -provider LOOPIA -timeout 3600s -start 25 -end 25
```

❓ Questionnnnnnnn ❓ 

So no output during those`IGNORE_*` test cases is normal? I get the impression there should be something there other than e.g.
```
=== RUN   TestDNSProviders/example.com/59:IGNORE_apex:ignore_label=apex
=== RUN   TestDNSProviders/example.com/59:IGNORE_apex:ignore_type=txt
=== RUN   TestDNSProviders/example.com/59:IGNORE_apex:ignore_target=1.2.3.4
=== RUN   TestDNSProviders/example.com/59:IGNORE_apex:ignore_manytypes
```

**Comment by Deraen** [comment]
@tlimoncelli Digitalocean tests are passing.

**Comment by juliusrickert** [comment]
HOSTINGDE's tests are all passing but `SOA:Modify_SOA_ns____` (which is persistently failing).

**Comment by kallsyms** [comment]
All passing for oracle.

**Comment by das7pad** [comment]
The tests are passing for HETZNER (including the DualProviders tests #2576. Tom, WDYT about merging them into here?).

I've also done a manual test (no-op preview and push of removal/addition of an AAAA record in a dual provider zone with HETZNER and ROUTE53).

**Comment by tlimoncelli** [comment]
> * [✅]  loopia @systemcrash

Thanks for looking into this!

The MX issue:  I didn't look deeply into it, but it could be that the dnscontrol code has a bug when just the priority changes. It could also be a bug at the provider's API (we've seen that elsewhere).  Let me know what the provider says.

The CAA issue: My guess is that they're validating the CAA data and our test data isn't passing their tests.  The integration tests use fake data but maybe we could make it less fake to pass this test.  Otherwise we can add `not("LOOPIA")` to the test to skip it.

> 
> ❓ Questionnnnnnnn ❓
> 
> So no output during those`IGNORE_*` test cases is normal? I get the impression there should be something there other than e.g.

Yes, that's typical.

Thanks!

**Comment by tlimoncelli** [comment]
@juliusrickert 

> HOSTINGDE's tests are all passing but `SOA:Modify_SOA_ns____` (which is persistently failing).

This can be one of two things.  (1) a bug in dnscontrol, (2) the API doesn't permit changing that record.

Please create a new issue for this and we can work on it there. (Looking at the code, I don't see the "ns" field mentioned)

Thanks!

**Comment by tlimoncelli** [comment]
@das7pad

> The tests are passing for HETZNER (including the DualProviders tests #2576. Tom, WDYT about merging them into here?).

I'm not sure I understand the question.

**Comment by das7pad** [comment]
> @das7pad
> 
> > The tests are passing for HETZNER (including the DualProviders tests #2576. Tom, WDYT about merging them into here?).
> 
> I'm not sure I understand the question.

The current revision of the PR branch is skipping the DualProvider tests. There is a chance that some provider does not play nice with the dual-provider code when diff1 has been removed and despite "manually" testing things (with the test skipped), we will not catch it here.

https://github.com/StackExchange/dnscontrol/blob/tlim_removediff1/integrationTest/integration_test.go#L342

I am suggesting to merge the master branch (which will un-skip the tests via the already merged #2576) to restore the tests here for manual testing.

**Comment by juliusrickert** [comment]
> @juliusrickert
> 
> > HOSTINGDE's tests are all passing but `SOA:Modify_SOA_ns____` (which is persistently failing).
> 
> This can be one of two things. (1) a bug in dnscontrol, (2) the API doesn't permit changing that record.
> 
> Please create a new issue for this and we can work on it there. (Looking at the code, I don't see the "ns" field mentioned)

Apparently, I already did: https://github.com/StackExchange/dnscontrol/issues/2243. GitHub's search fails to surface it when searching for `SOA:Modify_SOA_ns____` but searching for `modify soa` remediates it in a way.

**Comment by onlyhavecans** [comment]
All tests pass for DNSimple, and all my prod and test configs are working!

**Comment by tlimoncelli** [comment]
> das7pad

[das7pad](https://github.com/das7pad)

Ah! Thanks for the clarification.  I've merged as requested.

**Comment by tlimoncelli** [comment]
@onlyhavecans 
> All tests pass for DNSimple, and all my prod and test configs are working!

Thanks!

**Comment by tlimoncelli** [comment]
@juliusrickert
> Apparently, I already did: #2243. GitHub's search fails to surface it when searching for `SOA:Modify_SOA_ns____` but searching for `modify soa` remediates it in a way.

Thanks!

**Comment by costasd** [comment]
:heavy_check_mark:  ns1 works fine, both integration and my setup!

`master` @ 071fd2b7df
```
PASS
ok      github.com/StackExchange/dnscontrol/v4/integrationTest  163.631s
```

`tlim_removediff1` @ 0281b6eaf6
```
PASS
ok      github.com/StackExchange/dnscontrol/v4/integrationTest  184.511s
```

**Comment by svernick** [comment]
AKAMAIEDGEDNS is good.

% git branch
* tlim_removediff1

% git pull
Already up to date.

% go test -v -verbose -timeout 15m -provider AKAMAIEDGEDNS

PASS
ok  	github.com/StackExchange/dnscontrol/v4/integrationTest	514.643s

**Pull request merged**
