### PR TITLE
FEATURE: Enable "require()" function to accept json5 files

### LINKED ISSUE #2965: require json5 file?
**Is your feature request related to a problem? Please describe.**
I want to require json5 file

**Describe the solution you'd like**
unexpected token :

**Describe alternatives you've considered**
change to json suffix can fix

### PR DESCRIPTION
**Pull request by charliez0**
JSON5: fixes #2965

### CODE REVIEW

**Comment by charliez0** [comment]
Ready for review

**Comment by tlimoncelli** [comment]
I'm surprised (in a good way) that the code already accepts json5 files, and we just needed to accept the file extension.

Could you show a screen cap of this working?

**Comment by charliez0** [comment]
YES，tested with examples and works

```json
{
  "$schema": "../../schema.json",
  "description": "Project Description",
  "domain": "zve.me",
  "subdomain": "example",
  "owner": {
    repo: "https://github.com/username/repo",
    'email': 'hello@example.com',
    hexadecimal: 0xdecaf,
    leadingDecimalPoint: .8675309, andTrailing: 8675309.,
    positiveSign: +1
  },
  "expire": "2099-12-31",
  "record": {
    CNAME: ["example.com."],
    "HTTPS": [{
      "priority": 1,
      "target": ".",
      "value": "alpn=\"h3,h2\""
    }],
    "MX": [
      "mx1.example.com.",
      {
        "priority": 50,
        "value": "mx2.example.com."
      }
    ],
    "SSHFP": [{
      "algorithm": 4,
      "type": 2,
      "value": "123456789abcdef67890123456789abcdef67890123456789abcdef123456789"
    }],
    "SVCB": [{
      "priority": 1,
      "target": ".",
      "value": "alpn=\"h3,h2\""
    }],
    "TLSA": [{
      "usage": 3,
      "selector": 1,
      "type": 1,
      "value": "0123456789ABCDEF"
    }],
    "TXT": [
      "example_verification=1234567890"
    ],
  },
  "proxy": true,
  "nested": [{
    "subdomain": "a",
    "record": {
      "A": [
        "8.8.8.8",
        {
          "value": "8.8.4.4",
          "ttl": 3600
        }
      ],
      "AAAA": [
        "::4",
        {
          "value": "::8",
          "proxy": true
        }
      ]
    }
  },{
    "subdomain": "_sip._tcp",
    "record": {
      "SRV": [{
        "priority": 1,
        "weight": 1,
        "port": 10086,
        "target": "example.com."
      }]
    }
  },{
    "subdomain": "ns",
    "record": {
      "NS": [
        "example.com.",
        "example.org."
      ],
      "DS": [
        {
          "tag": 2371,
          "algorithm": 13,
          "digestType": 2,
          "digest": "0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF"
        }
      ]
    }
  }]
}
```

**Comment by charliez0** [comment]
@tlimoncelli I have tried to add most of json5 grammers to my test file and didn't affect anything

**Comment by tlimoncelli** [comment]
I've updated the documentation and added comments.  My work is here: https://github.com/StackExchange/dnscontrol/pull/3003

Please merge in my changes or if you prefer, I can merge my PR instead.

**Comment by charliez0** [comment]
> I've updated the documentation and added comments. My work is here: #3003
> 
> Please merge in my changes or if you prefer, I can merge my PR instead.

I'll close my ones and wait for yours

**Pull request closed without merging**
