### PR TITLE
DOCS: Simplified the provider URLs (providers)

### PR DESCRIPTION
**Pull request by cafferata**
Simplified the provider URLs. Example: `service-providers/providers/transip` = `provider/transip`.

Fixes https://github.com/StackExchange/dnscontrol/issues/2912

### providers

**Before**
[/service-providers/providers](https://docs.dnscontrol.org/service-providers/providers)

**After**
[/getting-started/providers](https://docs.dnscontrol.org/~/revisions/mZqsSSxD6fwKkl3d1xwo/getting-started/providers)

**After** (_redirect testcase_)
[/service-providers/providers](https://docs.dnscontrol.org/~/revisions/mZqsSSxD6fwKkl3d1xwo/service-providers/providers)

### provider/transip

**Before**
[/service-providers/providers/transip](https://docs.dnscontrol.org/service-providers/providers/transip)

**After**
[/provider/transip](https://docs.dnscontrol.org/~/revisions/mZqsSSxD6fwKkl3d1xwo/provider/transip)

**After** (_redirect testcase_)
[/service-providers/providers/transip](https://docs.dnscontrol.org/~/revisions/mZqsSSxD6fwKkl3d1xwo/service-providers/providers/transip)

### CODE REVIEW

**Comment by cafferata** [comment]
See also https://github.com/StackExchange/dnscontrol/pull/2913

**Comment by cafferata** [comment]
> Are you open to breaking old URLs?

_Originally posted by @tlimoncelli in https://github.com/StackExchange/dnscontrol/issues/2905#issuecomment-2041453176_

This is not necessary due to the additional [GitBook redirects: documentation/.gitbook.yaml](https://github.com/StackExchange/dnscontrol/pull/2914/files#diff-edbed1b874f27a3d77e12ea1fd6a529c6f5409937b9d6101c52eb73d210512df) 🥳

**Comment by cafferata** [comment]
Fixed merge conflict with https://github.com/StackExchange/dnscontrol/pull/2911. 🙈

**Comment by cafferata** [comment]
@tlimoncelli this pull request is ready for review (_and testing, see before/ater URL's_). 👍

**Review by tlimoncelli — APPROVED** [review]

**Pull request merged**
