### PR TITLE
fix(netlify): append . to records which point to hosts

### LINKED ISSUE #1825: [Netlify] Records are missing trailing dot
I was super excited to see @SphericalKat added support for Netlify!

I tried setting up my DNS config from my existing Netlify setup (using `dnscontrol get-zones --format=js netlify - mydomain.com` with the version of `dnscontrol` on the `master` branch). However, the records it generates are missing the trailing `.`, resulting in a bunch of errors when I tried to run `dnscontrol preview`.
I manually added the necessary dots and now `dnscontrol preview` reports a bunch of changes where `.` will be added to the records on Netlify’s end. I’m not sure if this is just a quirk of how the code parses the responses from Netlify or if Netlify stores DNS information differently from other providers.

### PR DESCRIPTION
**Pull request by SphericalKat**
Fixes #1825

### CODE REVIEW

**Comment by SphericalKat** [comment]
@j-f1 can you verify if this fixes your issue?

**Comment by j-f1** [comment]
That’s much better, although I think it also needs to be applied to MX (i.e. `MX('@', 10, 'in1-smtp.messagingengine.com')`)

```js
#7: MODIFY MX jedfox.com: (10 in1-smtp.messagingengine.com ttl=3600) -> (10 in1-smtp.messagingengine.com. ttl=3600)
#8: MODIFY MX jedfox.com: (20 in2-smtp.messagingengine.com ttl=3600) -> (20 in2-smtp.messagingengine.com. ttl=3600)
```

**Comment by SphericalKat** [comment]
My bad, fixed that.

**Comment by tlimoncelli** [comment]
Let me know if this is ready to merge (I'm a bit unclear)

**Pull request merged**
