### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by geek1011**
There are quite a few unused dependencies vendored. I removed them with `govendor remove +u`.

### CODE REVIEW

**Comment by Goder20** [comment]
Это интересно. Я думаю что нужно ознакомиться более подробно.

**Comment by geek1011** [comment]
@Goder20 These dependencies were probably still there because govendor doesn't automatically prune dependencies.

**Comment by captncraig** [comment]
🎱

**Comment by captncraig** [comment]
Thanks for the cleanup!

**Pull request merged**
