### PR TITLE
Ns1 provider

### PR DESCRIPTION
**Pull request by captncraig**

### CODE REVIEW

**Comment by ChrisMcKee** [comment]
Any chance of this merging in soon; or is there something outstanding?

**Comment by captncraig** [comment]
Other than fixing conflicts, I believe it was working. I just never had any urgency because we don't really use ns1. I'll fix it up, test against their staging, and hopefully merge it.

Hopefully I'll get an hour or so to do that in the next few days. Thanks for the poke.

**Comment by ChrisMcKee** [comment]
@captncraig cool I was merging it in but Priority is gone from Dns.go; is that now SrvPriority?

**Comment by tlimoncelli** [comment]
IIRC Priority became MxPreference and is only used for MX records.  SrvPriority is now stored just for SRV records.

**Comment by ChrisMcKee** [comment]
Works pretty well; I tried adding on the supports CAA in the code but I think the format they expect is breaking it.

https://ns1.com/articles/caa-records

The request in their v2 ui is ala 
```
{"answers":[{"answer":["0","issue","globalsign.com"]}],"zone":"somedomain","override_ttl":false,"type":"CAA","ttl":3600,"domain":"somedomain.com"}
```
Both of these produce no records; the CAA record will produce an error; the iodef record seems to simply get swallowed.

```
    CAA('@','issue','globalsign.com')
    // Report all violation to ivendi. If CA does not support
    // this record then refuse to issue any certificate
    CAA('@', 'iodef', 'mailto:admin@xxxxxx.com', CAA_CRITICAL)
```

**Comment by captncraig** [comment]
I got it compiling again, and am presently getting it to pass all the integration tests. Then I can look at CAA.

**Comment by ChrisMcKee** [comment]
@captncraig out of interest, what are you using to build/debug this? I'm using Gogland and it's a bit derpy trying to run the tests

**Comment by captncraig** [comment]
I use visual studio code. 
I run the integration tests by going to that directory and running:
`go test -v -verbose -provider NS1 -run TestDNS`
after setting the appropriate environment variables in the providers.json there.

**Comment by captncraig** [comment]
I'm having a lot of issues with the test suite right now though. A lot of random "record does not exist" responses, particularly on deletions. Almost like it takes time to fully propigate their system before records are fully "there".

Working on some sleep tricks to see if that gets past it.

**Comment by captncraig** [comment]
Nevermind, there was a pretty nasty bug I fixed. Tests are passing for me. I'll merge, and then you can work on other record types as you like @ChrisMcKee

**Comment by ChrisMcKee** [comment]
@captncraig Nice update; I'm working on UltraDNS integration as we're stuck with them as a secondary for the next 12months. With any luck, this won't drive me too derpy 😁

**Pull request merged**
