### PR TITLE
CICD: Bugfix: Changes introduced while tagging new releases cause git problems

### PR DESCRIPTION
**Pull request by tlimoncelli**
* Correct the `git push` statement used in producing releases.

### CODE REVIEW

**Comment by tlimoncelli** [comment]
CC @philpennock

**Comment by cafferata** [comment]
Just a thought, is it an idea to create the git tags via the GitHub interface?

https://github.com/StackExchange/dnscontrol/releases/new?tag=v4.8.3&title=v4.8.3&body=Notes

**Comment by tlimoncelli** [comment]
I prefer command line tools when making a release.  There may be a `gh` command equivalent to that URL.

**Comment by cafferata** [comment]
> There may be a gh command equivalent to that URL.

GitHub CLI is also an option: https://cli.github.com/manual/gh_release_create

**Review by philpennock — APPROVED** [review]

**Pull request merged**
