### PR TITLE
CHORE: Fix broken merge

### PR DESCRIPTION
**Pull request by tlimoncelli**

### CODE REVIEW

**Comment by tlimoncelli** [comment]
@juliusrickert I botched a merge.  This should fix it.  Please take a look and verify that everything works now.

**Comment by juliusrickert** [comment]
> Please take a look and verify that everything works now.

All tests are passing.

**Comment by tlimoncelli** [comment]
Thanks!

**Comment by cafferata** [comment]
@tlimoncelli, perhaps change the GitHub Pull request title?

```diff
-CHORE: Fix broken merge
+HOSTINGDE: Fix broken merge
```

**Pull request merged**
