### PR TITLE
Switch to Go 1.13 error wrapping

### LINKED ISSUE #589: Migrate from github.com/pkg/errors to Go 1.13's error wrapping.

### PR DESCRIPTION
**Pull request by geek1011**
- Replaced errors.Wrapf, errors.Wrap, and errors.Errorf with fmt.Errorf.
- Updated relevant imports.

closes #589

### CODE REVIEW

**Comment by geek1011** [comment]
https://stackoverflowoss.visualstudio.com/StackOSS/_build/results?buildId=772

**Comment by geek1011** [comment]
Rebased.

**Comment by geek1011** [comment]
Rebased again, and ready to be reviewed/merged. https://stackoverflowoss.visualstudio.com/StackOSS/_build/results?buildId=779 @tlimoncelli

**Comment by tlimoncelli** [comment]
Wow!  This is fantastic!  Thank you so much!

**Comment by geek1011** [comment]
No problem! I've used these regexps quite a few times for this.

**Pull request merged**
