### PR TITLE
ROUTE53: add R53_EVALUATE_TARGET_HEALTH to documentation summary

### PR DESCRIPTION
**Pull request by jonathanbouvier**
This new record modifier wasn't showing up in the documentation. Is there anywhere else that needs to be updated to get this working?

### CODE REVIEW

**Comment by tlimoncelli** [comment]
That's odd!  The table of contents (navigation) is manually generated, and this PR should fix that.

However I don't see the page that the TOC will link to.  It looks like the rebuild process worked (https://github.com/StackExchange/dnscontrol/actions/runs/7035630609/job/19146466173).  Let's see if merging this and re-pushing the pages forces it to work.  Failing that, it could be an issue with `build/generate/functionTypes.go`.

Tom

**Comment by tlimoncelli** [comment]
That fixed it!

https://docs.dnscontrol.org/language-reference/record-modifiers/service-provider-specific/amazon-route-53/r53_evaluate_target_health

**Comment by jonathanbouvier** [comment]
The link to R53_EVALUATE_TARGET_HEALTH on [R53_ALIAS](https://docs.dnscontrol.org/language-reference/domain-modifiers/service-provider-specific/amazon-route-53/r53_alias) is pointing to https://github.com/StackExchange/dnscontrol/blob/master/documentation/functions/record/R53_EVALUATE_TARGET_HEALTH.md instead of https://docs.dnscontrol.org/language-reference/record-modifiers/service-provider-specific/amazon-route-53/r53_evaluate_target_health

Any ideas what might be going wrong there?

**Comment by cafferata** [comment]
I suspect a missing backslash. I've never understood when this is necessary. I'm going after it.

**Comment by cafferata** [comment]
The question has been submitted to the support department.

**Pull request merged**
