### PR TITLE
PORKBUN: Remove unused function

### PR DESCRIPTION
**Pull request by tlimoncelli**
CC: @imlonghao

staticcheck reports:
```
api.go:103:27: func (*porkbunProvider).ping is unused (U1000)
```

Also fixed the import order by using "goimports" instead of "gofmt".  This is more consistent with other code.

### CODE REVIEW

**Comment by imlonghao** [comment]
How about just remove the unused function?

**Comment by tlimoncelli** [comment]
I've removed it.  Can you run the integration tests to verify that everything still works?

Thanks!

**Comment by imlonghao** [comment]
Integration tests LGTM

**Review by imlonghao — APPROVED** [review]

**Comment by tlimoncelli** [comment]
Thanks!

**Pull request merged**
